### ISSUE TITLE
english short words infer error

### ISSUE THREAD

**Issue by marson666** [FunAudioLLM/CosyVoice#12]
run inference code as shown below: 

```
ref_path="female01.wav"
cosyvoice = CosyVoice("pretrained_models/CosyVoice-300M")
# zero_shot usage
prompt_speech_16k = load_wav(ref_path, 16000)
output = cosyvoice.inference_cross_lingual(
    "hello world",
    prompt_speech_16k,
)
```

encounter error:
```
Traceback (most recent call last):
  File "my_local_infer.py", line 18, in <module>
    output = cosyvoice.inference_cross_lingual(
  File "/data/CosyVoice/cosyvoice/cli/cosyvoice.py", line 75, in inference_cross_lingual
    return {'tts_speech': torch.concat(tts_speeches, dim=1)}
RuntimeError: torch.cat(): expected a non-empty list of Tensors
```

**Comment by aluminumbox** [comment]
please add punctation at sentence end, for example 'hello world.'
