### ISSUE TITLE
error when run run.sh stage of train llm

### ISSUE THREAD

**Issue by cacard** [FunAudioLLM/CosyVoice#132]
env:
win11 + wsl2 + ubuntu22.04

log:

2024-07-14 10:15:10,023 DEBUG TRAIN Batch 0/49100 loss 1.675823 acc 0.226168 lr 0.00031911 grad_norm 3.311060 rank 0
WARNING:torch.distributed.elastic.rendezvous.dynamic_rendezvous:The node 'CA-ITX._27453_0' has failed to send a keep-alive heartbeat to the rendezvous '1986' due to an error of type RendezvousTimeoutError.
Traceback (most recent call last):
  File "/root/cosyvoice_git/examples/libritts/cosyvoice/cosyvoice/bin/train.py", line 136, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/cosyvoice_git/examples/libritts/cosyvoice/cosyvoice/bin/train.py", line 132, in main
    executor.train_one_epoc(model, optimizer, scheduler, train_data_loader, cv_data_loader, writer, info_dict, group_join)
  File "/root/cosyvoice_git/cosyvoice/utils/executor.py", line 68, in train_one_epoc
    info_dict = batch_backward(model, info_dict)
  File "/root/cosyvoice_git/cosyvoice/utils/train_utils.py", line 222, in batch_backward
    scaled_loss.backward()
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 27567) is killed by signal: Killed.
2024-07-14 10:15:39,199 DEBUG Attempting to acquire lock 139971725890496 on /root/.triton/autotune/Fp16Matmul_2d_kernel.pickle.lock
2024-07-14 10:15:39,199 DEBUG Lock 139971725890496 acquired on /root/.triton/autotune/Fp16Matmul_2d_kernel.pickle.lock
2024-07-14 10:15:39,200 DEBUG Attempting to release lock 139971725890496 on /root/.triton/autotune/Fp16Matmul_2d_kernel.pickle.lock
2024-07-14 10:15:39,200 DEBUG Lock 139971725890496 released on /root/.triton/autotune/Fp16Matmul_2d_kernel.pickle.lock
2024-07-14 10:15:39,202 DEBUG Attempting to acquire lock 139971725890448 on /root/.triton/autotune/Fp16Matmul_4d_kernel.pickle.lock
2024-07-14 10:15:39,202 DEBUG Lock 139971725890448 acquired on /root/.triton/autotune/Fp16Matmul_4d_kernel.pickle.lock
2024-07-14 10:15:39,202 DEBUG Attempting to release lock 139971725890448 on /root/.triton/autotune/Fp16Matmul_4d_kernel.pickle.lock
2024-07-14 10:15:39,202 DEBUG Lock 139971725890448 released on /root/.triton/autotune/Fp16Matmul_4d_kernel.pickle.lock
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 27476) of binary: /usr/bin/python3
ERROR:torch.distributed.elastic.multiprocessing.errors.error_handler:no error file defined for parent, to copy child error file (/tmp/torchelastic_gr56s5uf/1986_1pbeu24j/attempt_0/0/error.json)
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
cosyvoice/bin/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-14_10:15:39
  host      : CA-ITX.
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 27476)
  error_file: /tmp/torchelastic_gr56s5uf/1986_1pbeu24j/attempt_0/0/error.json
  traceback : Traceback (most recent call last):
    File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
      return f(*args, **kwargs)
    File "/root/cosyvoice_git/examples/libritts/cosyvoice/cosyvoice/bin/train.py", line 132, in main
      executor.train_one_epoc(model, optimizer, scheduler, train_data_loader, cv_data_loader, writer, info_dict, group_join)
    File "/root/cosyvoice_git/cosyvoice/utils/executor.py", line 68, in train_one_epoc
      info_dict = batch_backward(model, info_dict)
    File "/root/cosyvoice_git/cosyvoice/utils/train_utils.py", line 222, in batch_backward
      scaled_loss.backward()
    File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 487, in backward
      torch.autograd.backward(
    File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 200, in backward
      Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
      _error_if_any_worker_fails()
  RuntimeError: DataLoader worker (pid 27567) is killed by signal: Killed.

============================================================

**Comment by aluminumbox** [comment]
looks like your memory is not enough. Try reduce num_worker to 1

**Comment by cacard** [comment]
> looks like your memory is not enough. Try reduce num_worker to 1

yes, I tried before see your answer, it's work!
