### ISSUE TITLE
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

### ISSUE THREAD

**Issue by rlenain** [FunAudioLLM/CosyVoice#195]
When trying to run train:

```bash
Original Traceback (most recent call last):
    File "/home/raph/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
      data = fetcher.fetch(index)
    File "/home/raph/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 41, in fetch
      data = next(self.dataset_iter)
    File "/home/raph/repos/CosyVoice/cosyvoice/dataset/processor.py", line 322, in padding
      for sample in data:
    File "/home/raph/repos/CosyVoice/cosyvoice/dataset/processor.py", line 283, in dynamic_batch
      for sample in data:
    File "/home/raph/repos/CosyVoice/cosyvoice/dataset/processor.py", line 237, in sort
      for sample in data:
    File "/home/raph/repos/CosyVoice/cosyvoice/dataset/processor.py", line 209, in shuffle
      for sample in data:
    File "/home/raph/repos/CosyVoice/cosyvoice/dataset/processor.py", line 172, in parse_embedding
      sample['spk_embedding'] = torch.tensor(sample['spk_embedding'], dtype=torch.float32)
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
```

**Comment by inconnu1111** [comment]
你怎么解决的啊

**Comment by Dinxin** [comment]
大佬是如何解决的呢？
