### ISSUE TITLE
At the end of validation step: RuntimeError: Socket Timeout

### ISSUE THREAD

**Issue by rlenain** [FunAudioLLM/CosyVoice#199]
**Describe the bug**
At the end of the validation step:

```bash
cosyvoice/bin/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-23_13:04:49
  host      : papercup-ml-devbox-3.c.papercup-ml.internal
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3075589)
  error_file: /tmp/torchelastic_hux3i32t/1986_r7h8ulhb/attempt_0/0/error.json
  traceback : Traceback (most recent call last):
    File "/home/raph/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
      return f(*args, **kwargs)
    File "cosyvoice/bin/train.py", line 131, in main
      group_join = dist.new_group(backend="gloo", timeout=datetime.timedelta(seconds=args.timeout))
    File "/home/raph/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 3520, in new_group
      pg = _new_process_group_helper(
    File "/home/raph/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1009, in _new_process_group_helper
      backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
  RuntimeError: Socket Timeout
```

Any thoughts why? Running with the default config found in the libritts examples folder with some custom data.

**Comment by rlenain** [comment]
This error seems to only happen when using `torch_ddp`, but not when using `deepspeed`

**Comment by aluminumbox** [comment]
are you using exactly the same config file that we provided in libritts? is there more exception log?

**Comment by rlenain** [comment]
I'm using the exact same config yes

**Comment by aluminumbox** [comment]
this timeout maybe related with your data, use libritts data first, then check the data difference, most possible reason is that your data is too long (longer than 30s) or too short (shorter than 1s)

**Comment by rlenain** [comment]
okay thank you
