### ISSUE TITLE
按照文档运行测试程序时报错：ImportError: There is no such entity as whisper.tokenizer.get_tokenizer

### ISSUE THREAD

**Issue by qengli** [FunAudioLLM/CosyVoice#203]
装好环境后，运行下面代码
```
export PYTHONPATH=third_party/Matcha-TTS
```

```
from cosyvoice.cli.cosyvoice import CosyVoice
from cosyvoice.utils.file_utils import load_wav
import torchaudio

cosyvoice = CosyVoice('pretrained_models/CosyVoice-300M-SFT')
# sft usage
print(cosyvoice.list_avaliable_spks())
output = cosyvoice.inference_sft('你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？', '中文女')
torchaudio.save('sft.wav', output['tts_speech'], 22050)

cosyvoice = CosyVoice('pretrained_models/CosyVoice-300M')
# zero_shot usage, <|zh|><|en|><|jp|><|yue|><|ko|> for Chinese/English/Japanese/Cantonese/Korean
prompt_speech_16k = load_wav('zero_shot_prompt.wav', 16000)
output = cosyvoice.inference_zero_shot('收到好友从远方寄来的生日礼物，那份意外的惊喜与深深的祝福让我心中充满了甜蜜的快乐，笑容如花儿般绽放。', '希望你以后能够做的比我还好呦。', prompt_speech_16k)
torchaudio.save('zero_shot.wav', output['tts_speech'], 22050)
# cross_lingual usage
prompt_speech_16k = load_wav('cross_lingual_prompt.wav', 16000)
output = cosyvoice.inference_cross_lingual('<|en|>And then later on, fully acquiring that company. So keeping management in line, interest in line with the asset that\'s coming into the family is a reason why sometimes we don\'t buy the whole thing.', prompt_speech_16k)
torchaudio.save('cross_lingual.wav', output['tts_speech'], 22050)

cosyvoice = CosyVoice('pretrained_models/CosyVoice-300M-Instruct')
# instruct usage, support <laughter></laughter><strong></strong>[laughter][breath]
output = cosyvoice.inference_instruct('在面对挑战时，他展现了非凡的<strong>勇气</strong>与<strong>智慧</strong>。', '中文男', 'Theo \'Crimson\', is a fiery, passionate rebel leader. Fights with fervor for justice, but struggles with impulsiveness.')
torchaudio.save('instruct.wav', output['tts_speech'], 22050)
```

报错：

```
python ./test.py
2024-07-24 16:41:45,844 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2024-07-24 16:41:45,845 - modelscope - INFO - Loading ast index from /home/li/.cache/modelscope/ast_indexer
2024-07-24 16:41:45,945 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 f3b2ecdbd84d4837f6917685088b6d20 and a total number of 980 components indexed
transformer is not installed, please install it if you want to use related modules
/home/li/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
/home/li/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/diffusers/models/lora.py:393: FutureWarning: `LoRACompatibleLinear` is deprecated and will be removed in version 1.0.0. Use of `LoRACompatibleLinear` is deprecated. Please switch to PEFT backend by installing PEFT: `pip install peft`.
  deprecate("LoRACompatibleLinear", "1.0.0", deprecation_message)
Traceback (most recent call last):
  File "./test.py", line 5, in <module>
    cosyvoice = CosyVoice('pretrained_models/CosyVoice-300M-SFT')
  File "/home/li/workspace/CosyVoice/cosyvoice/cli/cosyvoice.py", line 29, in __init__
    configs = load_hyperpyyaml(f)
  File "/home/li/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/hyperpyyaml/core.py", line 188, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=loader)
  File "/home/li/.local/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/li/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 116, in get_single_data
    return self.construct_document(node)
  File "/home/li/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 120, in construct_document
    data = self.construct_object(node)
  File "/home/li/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/home/li/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "/home/li/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 633, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/li/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/home/li/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/li/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/home/li/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "/home/li/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/hyperpyyaml/core.py", line 491, in _construct_name
    raise ImportError("There is no such entity as %s" % callable_string)
ImportError: There is no such entity as whisper.tokenizer.get_tokenizer
```

**Comment by aluminumbox** [comment]
export PYTHONPATH, check faq.md

**Comment by beetaa** [comment]
I have the same issue

**Comment by thinkluck** [comment]
I also encountered the same problem

**Comment by SpenserCai** [comment]
https://github.com/FunAudioLLM/CosyVoice/issues/203#issuecomment-2249831883
see this
