### ISSUE TITLE
linux 安装deepspeed报错

### ISSUE THREAD

**Issue by hjj-lmx** [FunAudioLLM/CosyVoice#215]
ERROR: Command errored out with exit status 1:
     command: /home/vipuser/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5wxkkstg/deepspeed_2f291d7c2f5a4e648f413e91f6da95b1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5wxkkstg/deepspeed_2f291d7c2f5a4e648f413e91f6da95b1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_n3ly03d
         cwd: /tmp/pip-install-5wxkkstg/deepspeed_2f291d7c2f5a4e648f413e91f6da95b1/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5wxkkstg/deepspeed_2f291d7c2f5a4e648f413e91f6da95b1/setup.py", line 100, in <module>
        cuda_major_ver, cuda_minor_ver = installed_cuda_version()
      File "/tmp/pip-install-5wxkkstg/deepspeed_2f291d7c2f5a4e648f413e91f6da95b1/op_builder/builder.py", line 52, in installed_cuda_version
        output = subprocess.check_output([cuda_home + "/bin/nvcc", "-V"], universal_newlines=True)
      File "/home/vipuser/anaconda3/lib/python3.9/subprocess.py", line 424, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/home/vipuser/anaconda3/lib/python3.9/subprocess.py", line 505, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/home/vipuser/anaconda3/lib/python3.9/subprocess.py", line 951, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/home/vipuser/anaconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: ':/usr/local/cuda-11.8/bin/nvcc'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f0/84/a7b8ff287f7e1a5f01a010880b0bc5e58f718eaca784b4be592034eab3de/deepspeed-0.14.2.tar.gz#sha256=14d0cd5830bcb6d311ed5f8ce827cdaa678eebfc148ca744195a487df61270e3 (from https://pypi.org/simple/deepspeed/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement deepspeed==0.14.2; sys_platform == "linux" (from ud-texttospeech) (from versions: 0.3.1.dev1, 0.3.1.dev2, 0.3.1.dev3, 0.3.1.dev4, 0.3.1.dev5, 0.3.1.dev6, 0.3.1.dev7, 0.3.1.dev8, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10, 0.3.11, 0.3.12, 0.3.13, 0.3.14, 0.3.15, 0.3.16, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.5.7, 0.5.8, 0.5.9, 0.5.10, 0.6.0, 0.6.1, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 0.12.6, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4)
ERROR: No matching distribution found for deepspeed==0.14.2; sys_platform == "linux"

nvcc -V 是能找到cuda的版本信息的

**Comment by linyu0219** [comment]
顺便问一下 deepspeed 只是加速训练吗, 推理安装能提速吗
