### ISSUE TITLE
python setup.py egg_info did not run successfully.

### ISSUE THREAD

**Issue by yoyogis** [FunAudioLLM/CosyVoice#218]
Some error bellow occured when executed `pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ --trusted-host=mirrors.aliyun.com`: 

Collecting pynini==2.1.5
  Using cached https://mirrors.aliyun.com/pypi/packages/86/63/6a720dbdf4e7358baa2ab206a51693f9c6e83d174179a95539f501bd4a34/pynini-2.1.5.tar.gz (627 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/5f/qr1z_8n56dbgfyjzt_ltg1780000gn/T/pip-install-tj4nup7e/pynini_b41ab615102e4e98a45189923b3cbb1e/setup.py", line 22, in <module>
          from Cython.Build import cythonize
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by aklws** [comment]
you can try "pip install --upgrade setuptools"

**Comment by TeachCourse** [comment]
似乎没有效果，Windows10系统，执行
pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ --trusted-host=mirrors.aliyun.com
还是报错

**Comment by passion2021** [comment]
This may be because pynini cannot be installed.
* https://pypi.org/project/pynini/

**Comment by wangyugod** [comment]
这个有更新吗？我也是同样的问题，在Macos M1上出现的问题，上面说的方式都试过了，还是没有解决
