### ISSUE TITLE
runtime/python/server.py 运行后，调用api/inference/zero-shot，报错

### ISSUE THREAD

**Issue by hjj-lmx** [FunAudioLLM/CosyVoice#222]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/vipuser/anaconda3/envs/cosyvoice_test/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/vipuser/anaconda3/envs/cosyvoice_test/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/home/vipuser/anaconda3/envs/cosyvoice_test/lib/python3.8/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/vipuser/anaconda3/envs/cosyvoice_test/lib/python3.8/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/vipuser/anaconda3/envs/cosyvoice_test/lib/python3.8/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/vipuser/anaconda3/envs/cosyvoice_test/lib/python3.8/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/vipuser/anaconda3/envs/cosyvoice_test/lib/python3.8/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/vipuser/anaconda3/envs/cosyvoice_test/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/vipuser/anaconda3/envs/cosyvoice_test/lib/python3.8/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vipuser/anaconda3/envs/cosyvoice_test/lib/python3.8/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vipuser/anaconda3/envs/cosyvoice_test/lib/python3.8/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/vipuser/anaconda3/envs/cosyvoice_test/lib/python3.8/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/vipuser/anaconda3/envs/cosyvoice_test/lib/python3.8/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/vipuser/anaconda3/envs/cosyvoice_test/lib/python3.8/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/vipuser/anaconda3/envs/cosyvoice_test/lib/python3.8/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vipuser/anaconda3/envs/cosyvoice_test/lib/python3.8/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vipuser/anaconda3/envs/cosyvoice_test/lib/python3.8/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/vipuser/anaconda3/envs/cosyvoice_test/lib/python3.8/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/vipuser/anaconda3/envs/cosyvoice_test/lib/python3.8/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/UD/CosyVoice/runtime/python/fastapi/server.py", line 75, in zeroShot
    output = app.cosyvoice.inference_zero_shot(tts, prompt, prompt_speech_16k)
  File "/usr/local/UD/CosyVoice/runtime/python/fastapi/../../../cosyvoice/cli/cosyvoice.py", line 59, in inference_zero_shot
    model_input = self.frontend.frontend_zero_shot(i, prompt_text, prompt_speech_16k)
  File "/usr/local/UD/CosyVoice/runtime/python/fastapi/../../../cosyvoice/cli/frontend.py", line 142, in frontend_zero_shot
    speech_token, speech_token_len = self._extract_speech_token(prompt_speech_16k)
  File "/usr/local/UD/CosyVoice/runtime/python/fastapi/../../../cosyvoice/cli/frontend.py", line 79, in _extract_speech_token
    speech_token = self.speech_tokenizer_session.run(None, {self.speech_tokenizer_session.get_inputs()[0].name: feat.detach().cpu().numpy(),
  File "/home/vipuser/anaconda3/envs/cosyvoice_test/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Add node. Name:'/Add_2' Status Message: /Add_2: right operand cannot broadcast on dim 0 LeftShape: {1,2891,1280}, RightShape: {1500,1280}

**Comment by Charles0225** [comment]
遇到相似问题，请问是怎么解决的

**Comment by 987661913** [comment]
I also met you, how did you solve it?

**Comment by zjxcc** [comment]
> hjj-lmx
I also met you, how did you solve it?

**Comment by zjxcc** [comment]
@hjj-lmx
I also met you, how did you solve it?

**Comment by xiaomaofei** [comment]
me too呀
