### ISSUE TITLE
运行此命令时缺少matcha  python3 webui.py --port 50000 --model_dir pretrained_models/CosyVoice-300M

### ISSUE THREAD

**Issue by littlecutenainia** [FunAudioLLM/CosyVoice#227]
root@autodl-container-e3aa42aaff-16030c09:~/autodl-tmp/CosyVoice# python3 webui.py --port 50000 --model_dir pretrained_models/CosyVoice-300M
2024-07-31 14:58:56,677 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2024-07-31 14:58:56,678 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-07-31 14:58:56,729 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 c08808b83c7e7f2d9f5ed3bf8b60502f and a total number of 980 components indexed
transformer is not installed, please install it if you want to use related modules
/root/miniconda3/lib/python3.8/site-packages/torch/_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/pydoc.py", line 343, in safeimport
    module = __import__(path)
  File "/root/autodl-tmp/CosyVoice/cosyvoice/flow/flow_matching.py", line 16, in <module>
    from matcha.models.components.flow_matching import BASECFM
ModuleNotFoundError: No module named 'matcha'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "webui.py", line 190, in <module>
    cosyvoice = CosyVoice(args.model_dir)
  File "/root/autodl-tmp/CosyVoice/cosyvoice/cli/cosyvoice.py", line 29, in __init__
    configs = load_hyperpyyaml(f)
  File "/root/miniconda3/lib/python3.8/site-packages/hyperpyyaml/core.py", line 188, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=loader)
  File "/root/miniconda3/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/root/miniconda3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 121, in get_single_data
    return self.construct_document(node)
  File "/root/miniconda3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 126, in construct_document
    data = self.construct_object(node)
  File "/root/miniconda3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 154, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/root/miniconda3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 196, in construct_non_recursive_object
    for _dummy in generator:
  File "/root/miniconda3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 674, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/root/miniconda3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 445, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/root/miniconda3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 261, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/root/miniconda3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 154, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/root/miniconda3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 191, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "/root/miniconda3/lib/python3.8/site-packages/hyperpyyaml/core.py", line 480, in _construct_object
    args, kwargs = _load_node(loader, node)
  File "/root/miniconda3/lib/python3.8/site-packages/hyperpyyaml/core.py", line 434, in _load_node
    kwargs = loader.construct_mapping(node, deep=True)
  File "/root/miniconda3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 445, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/root/miniconda3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 261, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/root/miniconda3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 154, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/root/miniconda3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 191, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "/root/miniconda3/lib/python3.8/site-packages/hyperpyyaml/core.py", line 470, in _construct_object
    callable_ = pydoc.locate(callable_string)
  File "/root/miniconda3/lib/python3.8/pydoc.py", line 1625, in locate
    nextmodule = safeimport('.'.join(parts[:n+1]), forceload)
  File "/root/miniconda3/lib/python3.8/pydoc.py", line 358, in safeimport
    raise ErrorDuringImport(path, sys.exc_info())
pydoc.ErrorDuringImport: problem in cosyvoice.flow.flow_matching - ModuleNotFoundError: No module named 'matcha'

**Comment by aluminumbox** [comment]
check faq.md, export pythonpath

**Comment by 502dxceit** [comment]
you need this module: https://github.com/shivammehta25/Matcha-TTS/tree/main/matcha

**Comment by laochendeai** [comment]
> 你需要这个模块：https://github.com/shivammehta25/Matcha-TTS/tree/main/matcha

请问这个模型放在哪里啊

**Comment by 502dxceit** [comment]
项目的根目录下，把那个仓库的matcha文件夹整个放进去:
