### ISSUE TITLE
最后执行readme中的python代码,报错日志如下,请问是什么原因?

### ISSUE THREAD

**Issue by nicevlhjfihtqngkldl** [FunAudioLLM/CosyVoice#236]
错误日志
```
/root/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
/root/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/diffusers/models/lora.py:393: FutureWarning: `LoRACompatibleLinear` is deprecated and will be removed in version 1.0.0. Use of `LoRACompatibleLinear` is deprecated. Please switch to PEFT backend by installing PEFT: `pip install peft`.
  deprecate("LoRACompatibleLinear", "1.0.0", deprecation_message)
2024-08-01 21:48:02.137567384 [W:onnxruntime:, session_state.cc:1162 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-08-01 21:48:02.137604955 [W:onnxruntime:, session_state.cc:1164 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
Illegal instruction (core dumped)

```

**Comment by aluminumbox** [comment]
sorry, never meet this error

**Comment by HZ-GeLiang** [comment]
有解决吗? 我基于 Oracle VirtualBox 中安装的Ubuntu 在最后执行时也遇到了这个.

**Comment by HZ-GeLiang** [comment]
试试 pip uninstall ttsfrd
我用 gdb调试, 发现报错信息是在 ttsfrd中.

你可以试下
apt install gdb 

gdb --args python3 webui.py --port 50000 --model_dir pretrained_models/CosyVoice-300M
(gdb) run
(gdb) backtrace
看看是不是和我的错误信息一样

Thread 1 "python3" received signal SIGILL, Illegal instruction.
0x00007fff2d5d8e71 in ?? () from /root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ttsfrd.cpython-38-x86_64-linux-gnu.so
(gdb) backtrace
#0  0x00007fff2d5d8e71 in ?? () from /root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ttsfrd.cpython-38-x86_64-linux-gnu.so
#1  0x00007fff2d66b126 in ?? () from /root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ttsfrd.cpython-38-x86_64-linux-gnu.so
