### ISSUE TITLE
我遇到了这个问题，怎么解决

### ISSUE THREAD

**Issue by Zyg187** [FunAudioLLM/CosyVoice#249]
已经按照教程下载环境和模型
D:\anaconda\envs\cosyvoice\python.exe C:\Users\zyg\Desktop\CosyVoice_For_Windows-main\webui.py 
2024-08-05 16:21:07,422 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2024-08-05 16:21:07,424 - modelscope - INFO - Loading ast index from C:\Users\zyg\.cache\modelscope\ast_indexer
2024-08-05 16:21:07,545 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 1e11f8386aec41c41543daa60d3f8d92 and a total number of 980 components indexed
Traceback (most recent call last):
  File "C:\Users\zyg\Desktop\CosyVoice_For_Windows-main\webui.py", line 41, in <module>
    from cosyvoice.cli.cosyvoice import CosyVoice
  File "C:\Users\zyg\Desktop\CosyVoice_For_Windows-main\cosyvoice\cli\cosyvoice.py", line 20, in <module>
    from cosyvoice.cli.frontend import CosyVoiceFrontEnd
  File "C:\Users\zyg\Desktop\CosyVoice_For_Windows-main\cosyvoice\cli\frontend.py", line 18, in <module>
    import whisper
  File "D:\anaconda\envs\cosyvoice\lib\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
  File "D:\anaconda\envs\cosyvoice\lib\ctypes\__init__.py", line 363, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable

**Comment by aluminumbox** [comment]
never meet this, install environment again exactly according to readme

**Comment by web-masser** [comment]
我也遇到这个问题，请问怎么解决的呃？

**Comment by lonerlin** [comment]
pip uninstall whisper
pip install openai-whisper

**Comment by Conphyr** [comment]
我也遇到了差不多的问题...
![Image](https://github.com/user-attachments/assets/5add8683-721b-4028-a123-39a6daf22fd0)

**Comment by zqmx** [comment]
have any update ?
I have the same of issue....
