### ISSUE TITLE
部署完之后 运行webui.py 出现严重错误

### ISSUE THREAD

**Issue by 927133951** [FunAudioLLM/CosyVoice#253]
2024-08-06 15:47:00,910 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2024-08-06 15:47:00,913 - modelscope - INFO - Loading ast index from C:\Users\92713\.cache\modelscope\ast_indexer
2024-08-06 15:47:01,199 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 fb32e4533ef20d35974fbc7b107dd70a and a total number of 980 components indexed
Traceback (most recent call last):
  File "E:\ai\CosyVoice\webui.py", line 40, in <module>
    from cosyvoice.cli.cosyvoice import CosyVoice
  File "E:\ai\CosyVoice\cosyvoice\cli\cosyvoice.py", line 18, in <module>
    from cosyvoice.cli.frontend import CosyVoiceFrontEnd
  File "E:\ai\CosyVoice\cosyvoice\cli\frontend.py", line 18, in <module>
    import whisper
  File "C:\Users\92713\miniconda3\envs\cosyvoice\lib\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
  File "C:\Users\92713\miniconda3\envs\cosyvoice\lib\ctypes\__init__.py", line 363, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable

**Comment by aluminumbox** [comment]
seems like a windows related bug, install python environment again according to readme
