### ISSUE TITLE
Finetuning a model 

### ISSUE THREAD

**Issue by yiwei0730** [FunAudioLLM/CosyVoice#260]
Thank you very much for your excellent work!
I would like to ask you a question. I currently have two ideas, one is to finetune a multispeaker model and another one is to finetune the model alone.
The training method corresponding to the above two ideas is it better to only train flow.pt or to train llm.pt, flow.pt, hifi.pt all at once?

**Comment by yiwei0730** [comment]
I asked by the way. I trained llm.py directly and there was no error, but an error occurred when I trained flow.py.

Traceback (most recent call last):
 File "/workspace/yiwei/CosyVoice/examples/libritts/cosyvoice/cosyvoice/bin/train.py", line 136, in <module>
 main()
 File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
 return f(*args, **kwargs)
 File "/workspace/yiwei/CosyVoice/examples/libritts/cosyvoice/cosyvoice/bin/train.py", line 132, in main
 executor.train_one_epoc(model, optimizer, scheduler, train_data_loader, cv_data_loader, writer, info_dict, group_join)
 File "/workspace/yiwei/CosyVoice/cosyvoice/utils/executor.py", line 67, in train_one_epoc
 info_dict = batch_forward(model, batch_dict, info_dict)
 File "/workspace/yiwei/CosyVoice/cosyvoice/utils/train_utils.py", line 213, in batch_forward
 info_dict['loss_dict'] = model(batch, device)
 File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
 return forward_call(*args, **kwargs)
 File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
 output = self._run_ddp_forward(*inputs, **kwargs)
 File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1113, in _run_ddp_forward
 return module_to_run(*inputs, **kwargs)
 File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
 return forward_call(*args, **kwargs)
 File "/workspace/yiwei/CosyVoice/cosyvoice/flow/flow.py", line 85, in forward
 conds[i, :index] = feat[i, :index]
RuntimeError: The expanded size of the tensor (264) must match the existing size (80) at non-singleton dimension 1. Target sizes: [12, 264]. Tensor sizes: [12, 80]

**Comment by aluminumbox** [comment]
I think you only need to train llm.pt, the flow and hift model is already well trained

**Comment by yiwei0730** [comment]
Do you mean that if I want to train a new speaker, I only need to train llm.pt?
