### ISSUE TITLE
man，how do i make it work？

### ISSUE THREAD

**Issue by askie** [FunAudioLLM/CosyVoice#283]
(cosyvoice) gcf@gcf:/mnt/d/python/CosyVoice$ python3 webui.py --port 50000 --model_dir pretrained_models/CosyVoice-300M
2024-08-14 11:26:02,976 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2024-08-14 11:26:02,980 - modelscope - INFO - Loading ast index from /home/gcf/.cache/modelscope/ast_indexer
2024-08-14 11:26:02,997 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 71036b8baf6ba232175cc7c60065032e and a total number of 980 components indexed
failed to import ttsfrd, use WeTextProcessing instead
/home/gcf/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
/home/gcf/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/diffusers/models/lora.py:393: FutureWarning: `LoRACompatibleLinear` is deprecated and will be removed in version 1.0.0. Use of `LoRACompatibleLinear` is deprecated. Please switch to PEFT backend by installing PEFT: `pip install peft`.
  deprecate("LoRACompatibleLinear", "1.0.0", deprecation_message)
2024-08-14 11:26:07,496 INFO input frame rate=50
Traceback (most recent call last):
  File "webui.py", line 190, in <module>
    cosyvoice = CosyVoice(args.model_dir)
  File "/mnt/d/python/CosyVoice/cosyvoice/cli/cosyvoice.py", line 30, in __init__
    self.frontend = CosyVoiceFrontEnd(configs['get_tokenizer'],
  File "/mnt/d/python/CosyVoice/cosyvoice/cli/frontend.py", line 52, in __init__
    self.campplus_session = onnxruntime.InferenceSession(campplus_model, sess_options=option, providers=["CPUExecutionProvider"])
  File "/home/gcf/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/gcf/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 460, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrained_models/CosyVoice-300M/campplus.onnx failed:Protobuf parsing failed.

**Comment by zaiji100** [comment]
这是怎么解决的呀？同样的问题，按照 README 一步一步来的

**Comment by blair319** [comment]
这个解决了？我现在也遇到了这个问题，我已经安装 git lfs了
