### ISSUE TITLE
遇到whisper这个问题，重装了几次环境都不行，请问怎么解决？

### ISSUE THREAD

**Issue by web-masser** [FunAudioLLM/CosyVoice#316]
2024-08-24 13:31:04,052 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2024-08-24 13:31:04,052 - modelscope - INFO - Loading ast index from C:\Users\PC\.cache\modelscope\ast_indexer
2024-08-24 13:31:04,208 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 cb42de249bd167366594e9d164d91fde and a total number of 980 components indexed
transformer is not installed, please install it if you want to use related modules
Traceback (most recent call last):
  File "webui.py", line 30, in <module>
    from cosyvoice.cli.cosyvoice import CosyVoice
  File "E:\project\yuyinAi\CosyVoice\cosyvoice\cli\cosyvoice.py", line 18, in <module>
    from cosyvoice.cli.frontend import CosyVoiceFrontEnd
  File "E:\project\yuyinAi\CosyVoice\cosyvoice\cli\frontend.py", line 18, in <module>
    import whisper
  File "E:\miniconda3\envs\cosyvoice\lib\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
  File "E:\miniconda3\envs\cosyvoice\lib\ctypes\__init__.py", line 363, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable

**Comment by Eikwang** [comment]
如果没有其他的依赖冲突、缺失问题，cuda和cudnn版本匹配，path也没问题的话，就看下onnxruntime版本，重新装一下匹配cuda的onnxruntime和onnxruntime_gpu，这两个版本要一致。我就是这样解决的。

**Comment by walker-hyf** [comment]
pip uninstall whisper
pip install openai-whisper
