### ISSUE TITLE
There is no such entity as cosyvoice.utils.common.ras_sampling

### ISSUE THREAD

**Issue by oychao1988** [FunAudioLLM/CosyVoice#325]
Traceback (most recent call last):
  File "webui.py", line 190, in <module>
    cosyvoice = CosyVoice(args.model_dir)
  File "/root/autodl-tmp/CosyVoice/cosyvoice/cli/cosyvoice.py", line 29, in __init__
    configs = load_hyperpyyaml(f)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/hyperpyyaml/core.py", line 188, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=loader)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 116, in get_single_data
    return self.construct_document(node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 120, in construct_document
    data = self.construct_object(node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 633, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/hyperpyyaml/core.py", line 480, in _construct_object
    args, kwargs = _load_node(loader, node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/hyperpyyaml/core.py", line 434, in _load_node
    kwargs = loader.construct_mapping(node, deep=True)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/hyperpyyaml/core.py", line 491, in _construct_name
    raise ImportError("There is no such entity as %s" % callable_string)
ImportError: There is no such entity as cosyvoice.utils.common.ras_sampling

**Comment by jiaochunxiao** [comment]
The same issue is currently being encountered by me.

**Comment by zhoufengen** [comment]
me too! what can i do to fix it？

**Comment by sincerity711** [comment]
In the model file (https://www.modelscope.cn/models/iic/CosyVoice-300M/files/121c883104db335799d20e8c1fe7f4963c5a8058#diff_view_cosyvoice.yaml), a sampler was added to the LLM section, but this was not included in the code open-sourced on GitHub. Before open-sourcing, the model can be reverted to a previous version to resolve this

**Comment by zzhdbw** [comment]
@sincerity711 thank you, but how can we change the version of the model?

**Comment by aluminumbox** [comment]
comment ras_sampling in yaml, we will update the code by the end of the month

**Comment by wangtianrui** [comment]
How can I solve this problem?

**Comment by aluminumbox** [comment]
update your code, it should be fixed by now

**Comment by oychao1988** [comment]
> comment ras_sampling in yaml, we will update the code by the end of the month

![image](https://github.com/user-attachments/assets/30952172-cd36-4d91-b7ed-b2fad0aaa013)

thanks, it works!

**Comment by aigcchumen** [comment]
Error occurred when executing CosyVoiceNode:

name 'pseg' is not defined

File "E:\ComfyUI-aki-v1.3\execution.py", line 317, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "E:\ComfyUI-aki-v1.3\execution.py", line 192, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "E:\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
process_inputs(input_dict, i)
File "E:\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
results.append(getattr(obj, func)(**inputs))
File "E:\ComfyUI-aki-v1.3\custom_nodes\CosyVoice-ComfyUI\nodes.py", line 170, in generate
for out_dict in output:
File "E:\ComfyUI-aki-v1.3\custom_nodes\CosyVoice-ComfyUI\cosyvoice\cli\cosyvoice.py", line 52, in inference_sft
for i in self.frontend.text_normalize(tts_text, split=True):
File "E:\ComfyUI-aki-v1.3\custom_nodes\CosyVoice-ComfyUI\cosyvoice\cli\frontend.py", line 211, in text_normalize
text = normalize_zh(text)
File "E:\ComfyUI-aki-v1.3\custom_nodes\CosyVoice-ComfyUI\cosyvoice\cli\frontend.py", line 119, in normalize_zh
return process_ddd(text_normalize(remove_chinese_punctuation(text)))
File "E:\ComfyUI-aki-v1.3\custom_nodes\CosyVoice-ComfyUI\cosyvoice\cli\frontend.py", line 130, in process_ddd
word_list = [(word, flag) for word, flag in pseg.cut(text, use_paddle=False)]

关闭

**Comment by hwb96** [comment]
thank you，it works!

**Comment by waqian** [comment]
> > comment ras_sampling in yaml, we will update the code by the end of the month
> 
> ![image](https://private-user-images.githubusercontent.com/33217762/362988123-30952172-cd36-4d91-b7ed-b2fad0aaa013.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyODAxMzgsIm5iZiI6MTcyNTI3OTgzOCwicGF0aCI6Ii8zMzIxNzc2Mi8zNjI5ODgxMjMtMzA5NTIxNzItY2QzNi00ZDkxLWI3ZWQtYjJmYWQwYWFhMDEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDEyMjM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNjgxMTUyOGIxYjYxN2U3MTU4YmRjYWFjNzQ2ODUyZmQ3MWFkOTk0YzBjYTY2MDRjZjkxNmE5NmQ5MDk0MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j4NVWnmSkEFuKq88rrDFu_9CniHLRM0Sd2vc5x2CftY)
> 
> thanks, it works!

which file should be modified?

**Comment by skytodmoon** [comment]
mark， I met the same problem

**Comment by jtianling** [comment]
If you use the CosyVoice on mac with the https://github.com/v3ucn/CosyVoice_for_MacOs, and hard to upgrade the code to match the model. You could use 'git checkout 46b5c06a21fe6dfc3deedf7fc8fea4abe9c71e9b' in the folder 'pretrained_models/CosyVoice-300M' to fix it.
