### ISSUE TITLE
docker run fastapi can't start

### ISSUE THREAD

**Issue by quanpy** [FunAudioLLM/CosyVoice#326]
![QQ截图20240829174539](https://github.com/user-attachments/assets/a7f4cc95-e057-4586-9b58-cbc7f85d8812)

**Comment by quanpy** [comment]
INFO:     Will watch for changes in these directories: ['/opt/CosyVoice/CosyVoice/runtime/python/fastapi']
INFO:     Uvicorn running on http://127.0.0.1:50000 (Press CTRL+C to quit)
INFO:     Started reloader process [59] using WatchFiles
2024-08-29 09:48:27,530 - modelscope - INFO - PyTorch version 2.0.1 Found.
2024-08-29 09:48:27,531 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-08-29 09:48:27,548 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 2d704eea3111b0c614b649bbc9f40a99 and a total number of 980 components indexed
transformer is not installed, please install it if you want to use related modules
failed to import ttsfrd, use WeTextProcessing instead
INFO:     Started server process [62]
INFO:     Waiting for application startup.
/opt/conda/lib/python3.10/site-packages/torch/_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
ERROR:    Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/opt/conda/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/opt/CosyVoice/CosyVoice/runtime/python/fastapi/server.py", line 34, in lifespan

**Comment by aluminumbox** [comment]
fastapi is contributed by community developer. grpc is official supported, use grpc instead
