### ISSUE TITLE
代码更新到最新版本之后报错

### ISSUE THREAD

**Issue by jiachitor** [FunAudioLLM/CosyVoice#338]
When you git pull the code to the latest version, an error will be reported, which was normal before.

I searched and found that the error started from the commit 9ab298dd49c86e8eff12e3ce70ed90a5514c6193, which is "[add llm export script](https://github.com/FunAudioLLM/CosyVoice/commit/9ab298dd49c86e8eff12e3ce70ed90a55 14c6193)".

The development environment is Win11 virtual environment Ubuntu 22.04.3 LTS,  python 3.8.

具体报错内容是：
Traceback (most recent call last):
  File "webui.py", line 179, in <module>
    cosyvoice = CosyVoice(args.model_dir)
  File "/home/laobai/AiDev/@voiceAi/CosyVoice/cosyvoice/cli/cosyvoice.py", line 30, in __init__
    configs = load_hyperpyyaml(f)
  File "/home/laobai/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/hyperpyyaml/core.py", line 188, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=loader)
  File "/home/laobai/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/laobai/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 116, in get_single_data
    return self.construct_document(node)
  File "/home/laobai/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 120, in construct_document
    data = self.construct_object(node)
  File "/home/laobai/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/home/laobai/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "/home/laobai/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 633, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/laobai/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/home/laobai/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/laobai/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/home/laobai/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "/home/laobai/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/hyperpyyaml/core.py", line 481, in _construct_object
    return callable_(*args, **kwargs)
TypeError: ('Invalid argument to class cosyvoice.llm.llm.TransformerLM', "__init__() missing 1 required positional argument: 'sampling'")

**Comment by dengyao1** [comment]
重新下一下权重文件，缺了两个zip文件

**Comment by jiachitor** [comment]
> 重新下一下权重文件，缺了两个zip文件

谢谢了，可以了
