### ISSUE TITLE
依照安装说明安装后尝试开启cosy voice-instruct webui发生报错

### ISSUE THREAD

**Issue by Johnson8187** [FunAudioLLM/CosyVoice#339]
以下是错误讯息
`2024-08-31 15:33:09,546 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2024-08-31 15:33:09,547 - modelscope - INFO - Loading ast index from C:\Users\USER\.cache\modelscope\ast_indexer
2024-08-31 15:33:09,668 - modelscope - INFO - Updating the files for the changes of local files, first time updating will take longer time! Please wait till updating done!
2024-08-31 15:33:09,683 - modelscope - INFO - AST-Scanning the path "C:\Users\USER\miniconda3\envs\cosyvoice\Lib\site-packages\modelscope" with the following sub folders ['models', 'metrics', 'pipelines', 'preprocessors', 'trainers', 'msdatasets', 'exporters']
Traceback (most recent call last):
  File "C:\Users\USER\miniconda3\envs\cosyvoice\lib\site-packages\modelscope\utils\ast_utils.py", line 467, in _get_single_file_scan_result
    output = self.astScaner.generate_ast(file)
  File "C:\Users\USER\miniconda3\envs\cosyvoice\lib\site-packages\modelscope\utils\ast_utils.py", line 366, in generate_ast
    output = self.scan_import(node, show_offsets=False)
  File "C:\Users\USER\miniconda3\envs\cosyvoice\lib\site-packages\modelscope\utils\ast_utils.py", line 165, in scan_import
    local_out = _scan_import(el, type(el).__name__)
  File "C:\Users\USER\miniconda3\envs\cosyvoice\lib\site-packages\modelscope\utils\ast_utils.py", line 134, in _scan_import
    return self.scan_import(
  File "C:\Users\USER\miniconda3\envs\cosyvoice\lib\site-packages\modelscope\utils\ast_utils.py", line 152, in scan_import
    attr = getattr(node, field)
AttributeError: 'ClassDef' object has no attribute 'type_params'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "webui.py", line 27, in <module>
    from cosyvoice.cli.cosyvoice import CosyVoice
  File "C:\Users\USER\Documents\Project2024\CosyVoice\cosyvoice\cli\cosyvoice.py", line 17, in <module>
    from modelscope import snapshot_download
  File "C:\Users\USER\miniconda3\envs\cosyvoice\lib\site-packages\modelscope\__init__.py", line 4, in <module>
    from modelscope.utils.import_utils import (LazyImportModule,
  File "C:\Users\USER\miniconda3\envs\cosyvoice\lib\site-packages\modelscope\utils\__init__.py", line 1, in <module>
    from .hub import create_model_if_not_exist, read_config
  File "C:\Users\USER\miniconda3\envs\cosyvoice\lib\site-packages\modelscope\utils\hub.py", line 12, in <module>
    from modelscope.utils.config import Config
  File "C:\Users\USER\miniconda3\envs\cosyvoice\lib\site-packages\modelscope\utils\config.py", line 22, in <module>
    from modelscope.utils.import_utils import import_modules_from_file
  File "C:\Users\USER\miniconda3\envs\cosyvoice\lib\site-packages\modelscope\utils\import_utils.py", line 380, in <module>
    class LazyImportModule(ModuleType):
  File "C:\Users\USER\miniconda3\envs\cosyvoice\lib\site-packages\modelscope\utils\import_utils.py", line 383, in LazyImportModule
    AST_INDEX = load_index()
  File "C:\Users\USER\miniconda3\envs\cosyvoice\lib\site-packages\modelscope\utils\ast_utils.py", line 723, in load_index
    _update_index(index, files_mtime)
  File "C:\Users\USER\miniconda3\envs\cosyvoice\lib\site-packages\modelscope\utils\ast_utils.py", line 639, in _update_index
    updated_index = file_scanner.get_files_scan_results(updated_files)
  File "C:\Users\USER\miniconda3\envs\cosyvoice\lib\site-packages\modelscope\utils\ast_utils.py", line 533, in get_files_scan_results
    decorator_list, import_list = self._get_single_file_scan_result(
  File "C:\Users\USER\miniconda3\envs\cosyvoice\lib\site-packages\modelscope\utils\ast_utils.py", line 470, in _get_single_file_scan_result
    raise Exception(
Exception: During ast indexing the file C:\Users\USER\miniconda3\envs\cosyvoice\Lib\site-packages\modelscope\models\audio\aec\layers\activations.py, a related error excepted in the file C:\Users\USER\miniconda3\envs\cosyvoice\lib\site-packages\modelscope\utils\ast_utils.py at line: 152: "attr = getattr(node, field)" with error msg: "AttributeError: 'ClassDef' object has no attribute 'type_params'", please double check the origin file C:\Users\USER\miniconda3\envs\cosyvoice\Lib\site-packages\modelscope\models\audio\aec\layers\activations.py to see whether the file is correctly edited.
请按任意键继续 . . .`

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Johnson8187** [comment]
> 嗨兄弟，要解決您的問題，請嘗試此修復，我在另一個問題中看到它，https: [//app.mediafire.com/dqajf1x14ccfd](https://app.mediafire.com/dqajf1x14ccfd) 密碼： 安裝時更改我，您需要檢查安裝路徑並選擇 usx

This is a virus. I'm not dumb.

**Comment by aluminumbox** [comment]
seems like environment issue, never met this

**Comment by Johnson8187** [comment]
> seems like environment issue, never met this

Is there something I can do?

**Comment by Johnson8187** [comment]
> seems like environment issue, never met this

i found the solution https://github.com/modelscope/modelscope/issues/894
