### ISSUE TITLE
启动webui后，

### ISSUE THREAD

**Issue by zhlyxhygl** [FunAudioLLM/CosyVoice#382]
执行python3 webui.py --port 9886 --model_dir speech_tts/CosyVoice-300M后，在webui上点击任何按钮都会报超时错误，如下图
<img width="1321" alt="image" src="https://github.com/user-attachments/assets/56aa7417-1957-4ca4-8c63-7f7ac7f45ace">
控制台报错信息如下。该怎么解决啊
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/type_adapter.py", line 210, in __init__
    core_schema = _getattr_no_parents(type, '__pydantic_core_schema__')
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/type_adapter.py", line 98, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/gradio/route_utils.py", line 720, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/gradio/route_utils.py", line 736, in simple_response
    await self.app(scope, receive, send)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/fastapi/routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 639, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 813, in request_body_to_args
    fields_to_extract = get_model_fields(first_field.type_)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/fastapi/_compat.py", line 283, in get_model_fields
    return [
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/fastapi/_compat.py", line 284, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/fastapi/_compat.py", line 109, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/type_adapter.py", line 212, in __init__
    core_schema = _get_schema(type, config_wrapper, parent_depth=_parent_depth + 1)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/type_adapter.py", line 81, in _get_schema
    schema = gen.generate_schema(type_)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 499, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 734, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1749, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1817, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(source_type)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1899, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1895, in <lambda>
    lambda source, handler: handler(source)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(source_type)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1798, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 755, in _generate_schema_inner
    return self.match_type(obj)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 837, in match_type
    return self._match_generic_type(obj, origin)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 861, in _match_generic_type
    return self._union_schema(obj)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1149, in _union_schema
    choices.append(self.generate_schema(arg))
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 499, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 755, in _generate_schema_inner
    return self.match_type(obj)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 841, in match_type
    return self._unknown_type_schema(obj)
  File "/opt/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 402, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.7/u/schema-for-unknown-type

**Comment by Chevolier** [comment]
Same issue, any solutions?

**Comment by aluminumbox** [comment]
looks like a gradio problem, never seen it

**Comment by zhaoqingpu** [comment]
可能是一些依赖包版本问题，可以试试修改成这样:
pydantic==2.8.2
pydantic-core==2.20.1
fastapi==0.112.4

我这改完后就好了。

参考:  https://github.com/oobabooga/text-generation-webui/issues/6367#issuecomment-2333704584

**Comment by zhlyxhygl** [comment]
> 可能是一些依赖包版本问题，可以试试修改成这样: pydantic==2.8.2 pydantic-core==2.20.1 fastapi==0.112.4
> 
> 我这改完后就好了。
> 
> 参考: [oobabooga/text-generation-webui#6367 (comment)](https://github.com/oobabooga/text-generation-webui/issues/6367#issuecomment-2333704584)

感谢，把fastapi降级到0.112.4好了
