### ISSUE TITLE
运行报这个错怎么找问题所在？

### ISSUE THREAD

**Issue by woshi66** [FunAudioLLM/CosyVoice#383]
2024-09-12 09:30:52,827 - modelscope - INFO - PyTorch version 2.0.1 Found.
2024-09-12 09:30:52,828 - modelscope - INFO - Loading ast index from C:\Users\Administrator\.cache\modelscope\ast_indexer
2024-09-12 09:30:52,950 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 a2cc616f511160e4c1b7207398774aaa and a total number of 980 components indexed
failed to import ttsfrd, use WeTextProcessing instead
Traceback (most recent call last):
  File "D:\anaconda\envs\cosyvoicenew\lib\pydoc.py", line 343, in safeimport
    module = __import__(path)
  File "G:\python\CosyVoice\cosyvoice\flow\flow_matching.py", line 16, in <module>
    from matcha.models.components.flow_matching import BASECFM
ModuleNotFoundError: No module named 'matcha.models'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "webui.py", line 190, in <module>
    cosyvoice = CosyVoice(args.model_dir)
  File "G:\python\CosyVoice\cosyvoice\cli\cosyvoice.py", line 32, in __init__
    configs = load_hyperpyyaml(f)
  File "D:\anaconda\envs\cosyvoicenew\lib\site-packages\hyperpyyaml\core.py", line 188, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=loader)
  File "D:\anaconda\envs\cosyvoicenew\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "D:\anaconda\envs\cosyvoicenew\lib\site-packages\ruamel\yaml\constructor.py", line 116, in get_single_data
    return self.construct_document(node)
  File "D:\anaconda\envs\cosyvoicenew\lib\site-packages\ruamel\yaml\constructor.py", line 120, in construct_document
    data = self.construct_object(node)
  File "D:\anaconda\envs\cosyvoicenew\lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "D:\anaconda\envs\cosyvoicenew\lib\site-packages\ruamel\yaml\constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "D:\anaconda\envs\cosyvoicenew\lib\site-packages\ruamel\yaml\constructor.py", line 633, in construct_yaml_map
    value = self.construct_mapping(node)
  File "D:\anaconda\envs\cosyvoicenew\lib\site-packages\ruamel\yaml\constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "D:\anaconda\envs\cosyvoicenew\lib\site-packages\ruamel\yaml\constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "D:\anaconda\envs\cosyvoicenew\lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "D:\anaconda\envs\cosyvoicenew\lib\site-packages\ruamel\yaml\constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "D:\anaconda\envs\cosyvoicenew\lib\site-packages\hyperpyyaml\core.py", line 480, in _construct_object
    args, kwargs = _load_node(loader, node)
  File "D:\anaconda\envs\cosyvoicenew\lib\site-packages\hyperpyyaml\core.py", line 434, in _load_node
    kwargs = loader.construct_mapping(node, deep=True)
  File "D:\anaconda\envs\cosyvoicenew\lib\site-packages\ruamel\yaml\constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "D:\anaconda\envs\cosyvoicenew\lib\site-packages\ruamel\yaml\constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "D:\anaconda\envs\cosyvoicenew\lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "D:\anaconda\envs\cosyvoicenew\lib\site-packages\ruamel\yaml\constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "D:\anaconda\envs\cosyvoicenew\lib\site-packages\hyperpyyaml\core.py", line 470, in _construct_object
    callable_ = pydoc.locate(callable_string)
  File "D:\anaconda\envs\cosyvoicenew\lib\pydoc.py", line 1626, in locate
    nextmodule = safeimport('.'.join(parts[:n+1]), forceload)
  File "D:\anaconda\envs\cosyvoicenew\lib\pydoc.py", line 358, in safeimport
    raise ErrorDuringImport(path, sys.exc_info())
pydoc.ErrorDuringImport: problem in cosyvoice.flow.flow_matching - ModuleNotFoundError: No module named 'matcha.models'

运行报这个错怎么找问题所在？

**Comment by aklws** [comment]
少了'matcha.models'，别忘记把tts加到环境变量

**Comment by woshi66** [comment]
能具体一点吗？我把tts下载了也放对应目录里了  并且还根据别人的帖子吧model也放了还是报这个错

**Comment by aklws** [comment]
如果你是linux系统，那么把这句话export PYTHONPATH=third_party/Matcha-TTS 加到你的~/.bashrc 里面，然后source ~/.bashrc ;如果你是windows用户，在系统变量中找到PYTHONPATH并添加third_party/Matcha-TTS。
