### ISSUE TITLE
Failed to export onnx model from flow

### ISSUE THREAD

**Issue by zhangyike** [FunAudioLLM/CosyVoice#399]
env:
torch.__version__ = 2.0.1+cu118
onnx.__version__ = '1.16.0'
command: 
python cosyvoice/bin/export_onnx.py --model_dir $dir
error logs:
/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/diffusers/models/attention_processor.py:645: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if current_length != target_length:
/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/diffusers/models/attention_processor.py:660: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attention_mask.shape[0] < batch_size * head_size:
/apdcephfs_cq8/share_784792/users/yikezhang/public_repo/CosyVoice/examples/libritts/cosyvoice/cosyvoice/bin/../../third_party/Matcha-TTS/matcha/models/components/decoder.py:149: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert inputs.shape[1] == self.channels
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 1 ERROR ========================
ERROR: missing-standard-symbolic-function
=========================================
Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 18 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
None
<Set verbose=True to see more details>

Traceback (most recent call last):
  File "cosyvoice/bin/export_onnx.py", line 112, in <module>
    main()
  File "cosyvoice/bin/export_onnx.py", line 68, in main
    torch.onnx.export(
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/onnx/utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/onnx/utils.py", line 1117, in _model_to_graph
    graph = _optimize_graph(
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/onnx/utils.py", line 665, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/onnx/utils.py", line 1901, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 18 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

**Comment by aluminumbox** [comment]
use torch==2.2+, but onnx model rtf is not very stable

**Comment by JohnHerry** [comment]
> use torch==2.2+, but onnx model rtf is not very stable

请问现在转onnx的脚本程序， 对CosyVoice1和Cosyvoice2的 flow模型，都是通用的吗？

**Comment by JohnHerry** [comment]
@aluminumbox  请问官方开源的 flow onnx模型，是用GPU转换的，还是CPU转换的？我们想用它转TRT。目前本地环境下转换的onnx模型，测评阶段不通过。

**Comment by CJY1018** [comment]
> flow模型【CosyVocie1的 flow】转成了一个onnx文件，但是后续的测评阶段报错：
> 
> ```
> .conda/envs/cosydev/lib/python3.8/site-packages/torch/testing/_comparison.py", line 1524, in assert_close
>  raise error_metas[0].to_error(msg)
> AssertionError: Tensor-likes are not close!
> 
> Mismatched elements: 20 / 71200 (0.0%)
> Greatest absolute difference: 0.00882139801979065 at index (0, 0, 197) (up to 0.0001 allowed)
> Greatest relative difference: 0.13459473848342896 at index (0, 0, 81) (up to 0.01 allowed)
> ```
> 
> 第一个测评就是这样的结果，请问这是转换中哪里出现问题了吗？ 如何优化？

我也出现这个问题了，并且Mismatched elements有5.9%，请问怎么解决？
