### ISSUE TITLE
ampplus.onnx failed. File doesn't exist

### ISSUE THREAD

**Issue by sycao5** [FunAudioLLM/CosyVoice#414]
Try to run in the colab and see onnx related error. 

`
Traceback (most recent call last):
  File "/content/CosyVoice/webui.py", line 181, in <module>
    cosyvoice = CosyVoice(args.model_dir)
  File "/content/CosyVoice/cosyvoice/cli/cosyvoice.py", line 33, in __init__
    self.frontend = CosyVoiceFrontEnd(configs['get_tokenizer'],
  File "/content/CosyVoice/cosyvoice/cli/frontend.py", line 52, in __init__
    self.campplus_session = onnxruntime.InferenceSession(campplus_model, sess_options=option, providers=["CPUExecutionProvider"])
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 460, in `_create_inference_session`
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from pretrained_models/CosyVoice-300M/campplus.onnx failed:Load model pretrained_models/CosyVoice-300M/campplus.onnx failed. File doesn't exist`

**Comment by aluminumbox** [comment]
download model
