### ISSUE TITLE
RuntimeError: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by zhuermu** [FunAudioLLM/CosyVoice#42]
**Describe the bug**
python3 webui.py --port 50000 --model_dir pretrained_models/CosyVoice-300M 

the web page give a error tips:

and the console error stack like as below：**Additional context**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/FunAudioLLM/CosyVoice/assets/26120410/9dc904dc-b673-48df-88e2-347188b7a778)

**Additional context**
2024-07-08 15:38:37,990 INFO get sft inference request
Traceback (most recent call last):
  File "/data/home/xlw/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/gradio/queueing.py", line 521, in process_events
    response = await route_utils.call_process_api(
  File "/data/home/xlw/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/data/home/xlw/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/gradio/blocks.py", line 1945, in process_api
    result = await self.call_function(
  File "/data/home/xlw/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/gradio/blocks.py", line 1513, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/data/home/xlw/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/data/home/xlw/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/data/home/xlw/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/data/home/xlw/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/gradio/utils.py", line 831, in wrapper
    response = f(*args, **kwargs)
  File "webui.py", line 120, in generate_audio
    output = cosyvoice.inference_sft(tts_text, sft_dropdown)
  File "/data/home/xlw/workspace/github.com/CosyVoice/cosyvoice/cli/cosyvoice.py", line 51, in inference_sft
    model_output = self.model.inference(**model_input)
  File "/data/home/xlw/workspace/github.com/CosyVoice/cosyvoice/cli/model.py", line 58, in inference
    tts_speech = self.hift.inference(mel=tts_mel).cpu()
  File "/data/home/xlw/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/home/xlw/workspace/github.com/CosyVoice/cosyvoice/hifigan/generator.py", line 391, in inference
    return self.forward(x=mel)
  File "/data/home/xlw/workspace/github.com/CosyVoice/cosyvoice/hifigan/generator.py", line 348, in forward
    x = self.ups[i](x)
  File "/data/home/xlw/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/data/home/xlw/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 801, in forward
    return F.conv_transpose1d(
RuntimeError: GET was unable to find an engine to execute this computation

**Comment by aluminumbox** [comment]
we never meet such problem

**Comment by zxj329** [comment]
我也遇到这个问题了。你解决了吗？我怀疑是cuda版本的问题

**Comment by czydfj** [comment]
我也遇到了这个问题。这个问题解决了吗 @zxj329 @zhuermu

**Comment by xphh** [comment]
同遇到，网上查了一圈说是cuda的问题，但是cosyvoice2.0也没有说明对cuda有什么要求。具体怎么解决，跪求！

**Comment by xphh** [comment]
解决了，pip install -r requirement.txt后，还得手动用pip升级一下torch和torchaudio才行，醉了

**Comment by liuhuang31** [comment]
@xphh 你好，请问torch和torchaudio升级到那个版本
