### ISSUE TITLE
fastapi: client.py  Always reporting errors  ValueError: buffer size must be a multiple of element size

### ISSUE THREAD

**Issue by likuangyu01** [FunAudioLLM/CosyVoice#423]
**Describe the bug**
when i use fastapi run the client.py,  Always reporting errors
Traceback (most recent call last):
  File "client.py", line 98, in <module>
    main()
  File "client.py", line 59, in main
    tts_speech = torch.from_numpy(np.array(np.frombuffer(tts_audio, dtype=np.int16))).unsqueeze(dim=0)
ValueError: buffer size must be a multiple of element size

the client.py code :

    tts_audio = b''
    for r in response.iter_content(chunk_size=16000):
        tts_audio += r
    tts_speech = torch.from_numpy(np.array(np.frombuffer(tts_audio, dtype=np.int16))).unsqueeze(dim=0)

**Comment by aluminumbox** [comment]
how did you run the code, are you using readme example?

**Comment by likuangyu01** [comment]
> how did you run the code, are you using readme example?

已经解决了，在client.py中加了一点判断的代码
        tts_audio = b''
        for r in response.iter_content(chunk_size=16000):
            tts_audio += r

        # 检查字节长度
        if len(tts_audio) % 2 != 0:
            tts_audio = tts_audio[:-1]  # 去掉最后一个字节

**Comment by aluminumbox** [comment]
返回奇数个字节应该是有bug，你是官方推理示例吗？

**Comment by likuangyu01** [comment]
> 返回奇数个字节应该是有bug，你是官方推理示例吗？

是的，我用的是官方的推理示例， bug原因我找到了，是因为 没有配置 export MODEL_DIR=/path/CosyVoice/pretrained_models/CosyVoice-300M-SFT， 当client.py 发送请求后，server.py 运行model_output = cosyvoice.inference_sft(tts_text, spk_id)这段代码时，cosyvoice未被定义引起的bug，原因是if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--port',
                        type=int,
                        default=50000)
    parser.add_argument('--model_dir',
                        type=str,
                        default='iic/CosyVoice-300M',
                        help='local path or modelscope repo id')
    args = parser.parse_args()
    cosyvoice = CosyVoice(args.model_dir)  , cosyvoice 被定义在if __name__ == '__main__':条件之下，当client.py 发送请求调用async def inference_sft(tts_text: str = Form(), spk_id: str = Form()): 函数时，它并不能找到cosyvoice 对象，解决办法就是在直接在server.py文件里定义 cosyvoice = CosyVoice("/root/CosyVoice/pretrained_models/CosyVoice-300M") 为全局变量就可以了
