### ISSUE TITLE
运行examples/libritts/cosyvoice/run.sh报如下错误

### ISSUE THREAD

**Issue by kingulight** [FunAudioLLM/CosyVoice#468]
运行examples/libritts/cosyvoice/run.sh报如下错误：

Traceback (most recent call last):
  File "cosyvoice/bin/inference.py", line 115, in <module>
    main()
  File "cosyvoice/bin/inference.py", line 102, in main
    for model_output in model.inference(**model_input):
AttributeError: 'CosyVoiceModel' object has no attribute 'inference'

具体原因是cli/model.py没有实现inference的函数。

**Comment by KunZhou9646** [comment]
可以把model.inference替换成model.tts

**Comment by aluminumbox** [comment]
之前加vc后忘记修改了，后面会改一下，先改成model.tts
