### ISSUE TITLE
Question about extract_speech_token

### ISSUE THREAD

**Issue by osmankrblt** [FunAudioLLM/CosyVoice#478]
Hello, what should be the oonx_path for extract_speech_token.py?

**Comment by osmankrblt** [comment]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/media/hosman/Codes/Hexaops/TTS/./Other Models/CosyVoice/examples/turkishdataset/cosyvoice/tools/extract_speech_token.py", line 70, in <module>
    main(args)
  File "/media/hosman/Codes/Hexaops/TTS/./Other Models/CosyVoice/examples/turkishdataset/cosyvoice/tools/extract_speech_token.py", line 45, in main
    utt, speech_token = future.result()
                        ^^^^^^^^^^^^^^^
  File "/home/hosman/anaconda3/envs/audioHexaops/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/hosman/anaconda3/envs/audioHexaops/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/hosman/anaconda3/envs/audioHexaops/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/hosman/Codes/Hexaops/TTS/./Other Models/CosyVoice/examples/turkishdataset/cosyvoice/tools/extract_speech_token.py", line 37, in single_job
    ort_session.get_inputs()[1].name: np.array([feat.shape[2]], dtype=np.int32)})[0].flatten().tolist()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

I got this error. How can I solve this error
