### ISSUE TITLE
Zero-shot inference with additional instruction text

### ISSUE THREAD

**Issue by martinzwm** [FunAudioLLM/CosyVoice#509]
It could be helpful to control **speaking style** using prompt audio, and control **emotion** using instruction text. I attempted zero-shot inference by including the instruction text in the prompt using <endofprompt> as a separator: 
```
prompt_text = f"{instruction_text}<endofprompt>{prompt_text}"
```
However, this approach did not work as expected, and part of the prompt_text was included in the generated audio output.

If this feature is currently unsupported, could you provide suggestions or insights on how to finetune the model to handle both prompt audio and instruction text effectively? Thank you!

**Comment by pageinfoabout** [comment]
PLS Could some one explain why after i executed  this function i got this error?  


 1.   cd runtime/python
docker build -t cosyvoice:v1.0 .



2.   docker run -d --runtime=nvidia -p 50000:50000 cosyvoice:v1.0 /bin/bash -c "cd /opt/CosyVoice/CosyVoice/runtime/python/fastapi && python3 server.py --port 50000 --model_dir FunAudioLLM/Fun-CosyVoice3-0.5B-2512 && sleep infinity"


on my fastapi(port50000) server i have this error:

<img width="1317" height="363" alt="Image" src="https://github.com/user-attachments/assets/03814b28-dd5b-4f29-bf29-58830f383312" />

26-02-07 13:09:24,732 WARNING <|endofprompt|> not found in CosyVoice3 inference, check your input text
  0%|          | 0/1 [00:00<?, ?it/s]
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/opt/conda/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "/opt/conda/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
  |     return await self.app(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
  |     raise exc
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
  |     await self.app(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     raise exc
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
  |     await route.handle(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
  |     await self.app(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     raise exc
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
  |     await response(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 252, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 783, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 255, in wrap
    |     await func()
    |   File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 244, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/opt/conda/lib/python3.10/site-packages/starlette/concurrency.py", line 62, in iterate_in_threadpool
    |     yield await anyio.to_thread.run_sync(_next, as_iterator)
    |   File "/opt/conda/lib/python3.10/site-packages/anyio/to_thread.py", line 63, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |   File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2502, in run_sync_in_worker_thread
    |     return await future
    |   File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 986, in run
    |     result = context.run(func, *args)
    |   File "/opt/conda/lib/python3.10/site-packages/starlette/concurrency.py", line 51, in _next
    |     return next(iterator)
    |   File "/opt/CosyVoice/CosyVoice/runtime/python/fastapi/server.py", line 41, in generate_data
    |     for i in model_output:
    |   File "/opt/CosyVoice/CosyVoice/runtime/python/fastapi/../../../cosyvoice/cli/cosyvoice.py", line 98, in inference_zero_shot
    |     model_input = self.frontend.frontend_zero_shot(i, prompt_text, prompt_wav, self.sample_rate, zero_shot_spk_id)
    |   File "/opt/CosyVoice/CosyVoice/runtime/python/fastapi/../../../cosyvoice/cli/frontend.py", line 172, in frontend_zero_shot
    |     speech_feat, speech_feat_len = self._extract_speech_feat(prompt_wav)
    |   File "/opt/CosyVoice/CosyVoice/runtime/python/fastapi/../../../cosyvoice/cli/frontend.py", line 121, in _extract_speech_feat
    |     speech = load_wav(prompt_wav, 24000)
    |   File "/opt/CosyVoice/CosyVoice/runtime/python/fastapi/../../../cosyvoice/utils/file_utils.py", line 45, in load_wav
    |     speech, sample_rate = torchaudio.load(wav, backend='soundfile')
    |   File "/opt/conda/lib/python3.10/site-packages/torchaudio/_backend/utils.py", line 205, in load
    |     return backend.load(uri, frame_offset, num_frames, normalize, channels_first, format, buffer_size)
    |   File "/opt/conda/lib/python3.10/site-packages/torchaudio/_backend/soundfile.py", line 27, in load
    |     return soundfile_backend.load(uri, frame_offset, num_frames, normalize, channels_first, format)
    |   File "/opt/conda/lib/python3.10/site-packages/torchaudio/_backend/soundfile_backend.py", line 221, in load
    |     with soundfile.SoundFile(filepath, "r") as file_:
    |   File "/opt/conda/lib/python3.10/site-packages/soundfile.py", line 658, in __init__
    |     self._file = self._open(file, mode_int, closefd)
    |   File "/opt/conda/lib/python3.10/site-packages/soundfile.py", line 1212, in _open
    |     raise TypeError("Invalid file: {0!r}".format(self.name))
    | TypeError: Invalid file: tensor([[-1.9854e-04, -3.0836e-04, -7.2703e-05,  ...,  1.9053e-08,
    |           7.4869e-09,  2.1602e-10]])
    +------------------------------------
who can share me solution)))
