### ISSUE TITLE
webui运行报错，更新huggingface_hub后依旧报错，请问如何解决

### ISSUE THREAD

**Issue by yangpeng666** [FunAudioLLM/CosyVoice#527]
python3 webui.py --port 7865 --model_dir pretrained_models/CosyVoice-300M
2024-10-21 12:16:38,971 - modelscope - INFO - PyTorch version 2.0.1 Found.
2024-10-21 12:16:38,971 - modelscope - INFO - Loading ast index from /home/dl/.cache/modelscope/ast_indexer
2024-10-21 12:16:38,971 - modelscope - INFO - No valid ast index found from /home/dl/.cache/modelscope/ast_indexer, generating ast index from prebuilt!
2024-10-21 12:16:39,012 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 11b7055b4d9510a8a4fc9e68ff84580f and a total number of 980 components indexed
Traceback (most recent call last):
  File "/home/dl/micromamba/envs/cosyvoice/lib/python3.8/pydoc.py", line 343, in safeimport
    module = __import__(path)
  File "/home/dl/data/FunAudioLLM/CosyVoice/cosyvoice/flow/flow_matching.py", line 16, in <module>
    from matcha.models.components.flow_matching import BASECFM
  File "/home/dl/data/FunAudioLLM/CosyVoice/third_party/Matcha-TTS/matcha/models/components/flow_matching.py", line 6, in <module>
    from matcha.models.components.decoder import Decoder
  File "/home/dl/data/FunAudioLLM/CosyVoice/third_party/Matcha-TTS/matcha/models/components/decoder.py", line 8, in <module>
    from diffusers.models.activations import get_activation
  File "/home/dl/micromamba/envs/cosyvoice/lib/python3.8/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/home/dl/micromamba/envs/cosyvoice/lib/python3.8/site-packages/diffusers/utils/__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/home/dl/micromamba/envs/cosyvoice/lib/python3.8/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/home/dl/micromamba/envs/cosyvoice/lib/python3.8/site-packages/huggingface_hub/__init__.py)

**Comment by aluminumbox** [comment]
版本问题，尝试换个版本

**Comment by glennchina** [comment]
使用0.25.2就OK了

**Comment by bitoChan** [comment]
> 使用0.25.2就OK了

這對我有效。
requirement 具體如下：--extra-index-url https://download.pytorch.org/whl/cu118
conformer==0.3.2
deepspeed==0.14.2; sys_platform == 'linux'
diffusers==0.27.2
gdown==5.1.0
gradio==4.32.2
grpcio==1.57.0
grpcio-tools==1.57.0
hydra-core==1.3.2
HyperPyYAML==1.2.2
inflect==7.3.1
librosa==0.10.2
lightning==2.2.4
matplotlib==3.7.5
modelscope==1.19.2
networkx==3.1
omegaconf==2.3.0
onnx==1.16.0
onnxruntime==1.16.0
openai-whisper==20231117
protobuf==4.25
pydantic==2.7.0
rich==13.7.1
soundfile==0.12.1
tensorboard==2.14.0
torch==2.0.1
torchaudio==2.0.2
uvicorn==0.30.0
wget==3.2
fastapi==0.111.0
fastapi-cli==0.0.4
WeTextProcessing==1.0.3
huggingface_hub==0.25.2

**Comment by Wauplin** [comment]
Hey there, maintainer of `huggingface_hub` here. Sorry for all the trouble this breaking change introduced. The best 
 -and future proof- solution to fix this is to **upgrade `diffusers` version** to a more recent version (>=0.29.0).

```
pip install "diffusers>=0.29.0"
```

This fixed version dates back to June 2024. The issue with pinning `huggingface_hub` to an old version is that it might conflict with future versions of diffusers/transformers.

Hope this will prove useful :pray:
