### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by cc228** [FunAudioLLM/CosyVoice#609]
报错
A clear and concise dTraceback (most recent call last):
  File "D:\langchao\Audio\CosyVoice\test.py", line 7, in <module>
    cosyvoice = CosyVoice('pretrained_models/CosyVoice-300M')
  File "D:\langchao\Audio\CosyVoice\cosyvoice\cli\cosyvoice.py", line 33, in __init__
    self.frontend = CosyVoiceFrontEnd(configs['get_tokenizer'],
  File "D:\langchao\Audio\CosyVoice\cosyvoice\cli\frontend.py", line 73, in __init__
    self.zh_tn_model = ZhNormalizer(remove_erhua=False, full_to_half=False)
  File "D:\anaconda\envs\CosyVoice\lib\site-packages\tn\chinese\normalizer.py", line 53, in __init__
    self.build_fst('zh_tn', cache_dir, overwrite_cache)
  File "D:\anaconda\envs\CosyVoice\lib\site-packages\tn\processor.py", line 85, in build_fst
    os.makedirs(cache_dir, exist_ok=True)
  File "D:\anaconda\envs\CosyVoice\lib\os.py", line 210, in makedirs
    head, tail = path.split(name)
  File "D:\anaconda\envs\CosyVoice\lib\ntpath.py", line 211, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not MultiplexedPathescription of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aluminumbox** [comment]
没遇到过，看上去是wetextprocessing没装好，重装试试

**Comment by rex657** [comment]
consider to update the module path pulling function in both
{ComfyUI portable}\python_embeded\Lib\site-packages\tn\chinese\nomalizer.py
{ComfyUI portable}\python_embeded\Lib\site-packages\tn\english\nomalizer.py
locate line for files
```
        if cache_dir is None:
            cache_dir = files("tn")**._paths[0]**
```
Add path selector to convert MultiplexedPath to OS path, and remember to save and restart ComfyUI
