### ISSUE TITLE
wsl  部署和导入问题报错多次

### ISSUE THREAD

**Issue by longllovers** [FunAudioLLM/CosyVoice#64]
**Describe the bug**
在构建cosyvoice类时候出现问题，对应这句cosyvoice = CosyVoice('pretrained_models/CosyVoice-300M-SFT')

报错内容，>>> cosyvoice = CosyVoice('pretrained_models/CosyVoice-300M-SFT')
/home/ialover/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
/home/ialover/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/diffusers/models/lora.py:393: FutureWarning: `LoRACompatibleLinear` is deprecated and will be removed in version 1.0.0. Use of `LoRACompatibleLinear` is deprecated. Please switch to PEFT backend by installing PEFT: `pip install peft`.
  deprecate("LoRACompatibleLinear", "1.0.0", deprecation_message)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ialover/CosyVoice/cosyvoice/cli/cosyvoice.py", line 30, in __init__
    self.frontend = CosyVoiceFrontEnd(configs['get_tokenizer'],
  File "/home/ialover/CosyVoice/cosyvoice/cli/frontend.py", line 49, in __init__
    self.campplus_session = onnxruntime.InferenceSession(campplus_model, sess_options=option, providers=["CPUExecutionProvider"])
  File "/home/ialover/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/ialover/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrained_models/CosyVoice-300M-SFT/campplus.onnx failed:Protobuf parsing failed.  请求帮助，不知道如何解决

**Comment by aluminumbox** [comment]
check your protobuf version according to requirements.txt

**Comment by robinspt** [comment]
(cosyvoice) robinspt@DESKTOP-LTSC:~/CosyVoice$ pip install --upgrade protobuf==4.25
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: protobuf==4.25 in /home/robinspt/miniconda3/envs/cosyvoice/lib/python3.8/site-packages (4.25.0)
(cosyvoice) robinspt@DESKTOP-LTSC:~/CosyVoice$ python3 webui.py --port 50000 --model_dir pretrained_models/CosyVoice-300M
2024-07-09 22:23:52,939 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2024-07-09 22:23:52,939 - modelscope - INFO - Loading ast index from /home/robinspt/.cache/modelscope/ast_indexer
2024-07-09 22:23:52,974 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 fc9bda68762f0effdb9d3b6cfc4092f3 and a total number of 980 components indexed
transformer is not installed, please install it if you want to use related modules
/home/robinspt/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
/home/robinspt/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/diffusers/models/lora.py:393: FutureWarning: `LoRACompatibleLinear` is deprecated and will be removed in version 1.0.0. Use of `LoRACompatibleLinear` is deprecated. Please switch to PEFT backend by installing PEFT: `pip install peft`.
  deprecate("LoRACompatibleLinear", "1.0.0", deprecation_message)
2024-07-09 22:23:59,123 INFO input frame rate=50
Traceback (most recent call last):
  File "webui.py", line 181, in <module>
    cosyvoice = CosyVoice(args.model_dir)
  File "/home/robinspt/CosyVoice/cosyvoice/cli/cosyvoice.py", line 30, in __init__
    self.frontend = CosyVoiceFrontEnd(configs['get_tokenizer'],
  File "/home/robinspt/CosyVoice/cosyvoice/cli/frontend.py", line 49, in __init__
    self.campplus_session = onnxruntime.InferenceSession(campplus_model, sess_options=option, providers=["CPUExecutionProvider"])
  File "/home/robinspt/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/robinspt/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 460, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrained_models/CosyVoice-300M/campplus.onnx failed:Protobuf parsing failed.
(cosyvoice) robinspt@DESKTOP-LTSC:~/CosyVoice$ pip show protobuf
Name: protobuf
Version: 4.25.0
Summary:
Home-page: https://developers.google.com/protocol-buffers/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: 3-Clause BSD License
Location: /home/robinspt/miniconda3/envs/cosyvoice/lib/python3.8/site-packages
Requires:
Required-by: grpcio-tools, onnxruntime-gpu, tensorboard

**Comment by robinspt** [comment]
我好像也遇到同样问题，在wsl2上尝试运行的
```
(cosyvoice) robinspt@DESKTOP-LTSC:~/CosyVoice$ python3 webui.py --port 50000 --model_dir pretrained_models/CosyVoice-300M
2024-07-09 22:23:52,939 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2024-07-09 22:23:52,939 - modelscope - INFO - Loading ast index from /home/robinspt/.cache/modelscope/ast_indexer
2024-07-09 22:23:52,974 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 fc9bda68762f0effdb9d3b6cfc4092f3 and a total number of 980 components indexed
transformer is not installed, please install it if you want to use related modules
/home/robinspt/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
/home/robinspt/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/diffusers/models/lora.py:393: FutureWarning: `LoRACompatibleLinear` is deprecated and will be removed in version 1.0.0. Use of `LoRACompatibleLinear` is deprecated. Please switch to PEFT backend by installing PEFT: `pip install peft`.
  deprecate("LoRACompatibleLinear", "1.0.0", deprecation_message)
2024-07-09 22:23:59,123 INFO input frame rate=50
Traceback (most recent call last):
  File "webui.py", line 181, in <module>
    cosyvoice = CosyVoice(args.model_dir)
  File "/home/robinspt/CosyVoice/cosyvoice/cli/cosyvoice.py", line 30, in __init__
    self.frontend = CosyVoiceFrontEnd(configs['get_tokenizer'],
  File "/home/robinspt/CosyVoice/cosyvoice/cli/frontend.py", line 49, in __init__
    self.campplus_session = onnxruntime.InferenceSession(campplus_model, sess_options=option, providers=["CPUExecutionProvider"])
  File "/home/robinspt/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/robinspt/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 460, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrained_models/CosyVoice-300M/campplus.onnx failed:Protobuf parsing failed.
```
检查 Protobuf 版本与requirements.txt是一致的
```
(cosyvoice) robinspt@DESKTOP-LTSC:~/CosyVoice$ pip show protobuf
Name: protobuf
Version: 4.25.0
Summary:
Home-page: https://developers.google.com/protocol-buffers/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: 3-Clause BSD License
Location: /home/robinspt/miniconda3/envs/cosyvoice/lib/python3.8/site-packages
Requires:
Required-by: grpcio-tools, onnxruntime-gpu, tensorboard
```

**Comment by aluminumbox** [comment]
make sure git lfs installed, download model again, the onnx file you have downloaded is fake

**Comment by j2l** [comment]
Just had the same issue.

**Comment by metalik** [comment]
got this problem too
and it's resolved after install git-lfs

**Comment by YJCmote1** [comment]
> make sure git lfs installed, download model again, the onnx file you have downloaded is fake

after git lfs installed, all the pretrained model should be deleted, then download them again. I worked by doing like this.
