### ISSUE TITLE
模型微调，执行extract_speech_token出现报错

### ISSUE THREAD

**Issue by wjddd** [FunAudioLLM/CosyVoice#67]
运行tools/extract_speech_token.py出现以下报错：
```shell
Traceback (most recent call last):
  File "extract_speech_token.py", line 64, in <module>
    main(args)
  File "extract_speech_token.py", line 54, in main
    speech_token = ort_session.run(None, {ort_session.get_inputs()[0].name: feat.detach().cpu().numpy(),
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: feats for the following indices
 index: 0 Got: 2 Expected: 1
 Please fix either the inputs or the model.
 ```
 请问这个是模型的问题还是数据的问题？

**Comment by wjddd** [comment]
已解决，训练音频要求为单声道。

**Comment by clearlove-civ6** [comment]
感
