### ISSUE TITLE
配置bug

### ISSUE THREAD

**Issue by Guanjunyun** [FunAudioLLM/CosyVoice#696]
![图片_1733279876494](https://github.com/user-attachments/assets/5b0eb9e7-c5b9-43a2-b2b0-0bf1fcfcc73a)
我不清楚，这是哪里错了，我的项目是git直接下载的，但模型文件夹不是git下载的，Matcha-TTS已经下载好了，是需要安装transformer吗？

**Comment by iloveuaa** [comment]
你跟我一样的报错。新版本安装方法可能有问题了。

**Comment by aluminumbox** [comment]
更新代码更新模型，模型里的所有东西都要更新不要遗漏

**Comment by iloveuaa** [comment]
> 更新代码更新模型，模型里的所有东西都要更新不要遗漏

我是今天早上才试过的，模型是昨天下的

**Comment by Guanjunyun** [comment]
> > 更新代码更新模型，模型里的所有东西都要更新不要遗漏
> 
> 我是今天早上才试过的，模型是昨天下的
加下Q方便讨论：2434035776

**Comment by Guanjunyun** [comment]
> 更新代码更新模型，模型里的所有东西都要更新不要遗漏
确实有用，已经可以run了

**Comment by iloveuaa** [comment]
> > 更新代码更新模型，模型里的所有东西都要更新不要遗漏
> > 确实有用，已经可以run了

```
2024-12-04 19:24:34,111 INFO get zero_shot inference request
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]2024-12-04 19:24:35,713 INFO synthesis text 我是通义实验室语音团队全新推出的生成式语音大模型,提供舒适自然的语音合成能力。
Exception in thread Thread-9:
Traceback (most recent call last):
  File "C:\Users\HO\miniconda3\envs\cosyvoice\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\HO\miniconda3\envs\cosyvoice\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\AI\CosyVoice\cosyvoice\cli\model.py", line 93, in llm_job
    for i in self.llm.inference(text=text.to(self.device),
  File "C:\Users\HO\miniconda3\envs\cosyvoice\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "E:\AI\CosyVoice\cosyvoice\llm\llm.py", line 172, in inference
    text, text_len = self.encode(text, text_len)
  File "E:\AI\CosyVoice\cosyvoice\llm\llm.py", line 75, in encode
    encoder_out, encoder_mask = self.text_encoder(text, text_lengths, decoding_chunk_size=1, num_decoding_left_chunks=-1)
  File "C:\Users\HO\miniconda3\envs\cosyvoice\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/cosyvoice/transformer/encoder/___torch_mangle_5.py", line 22, in forward
    masks = torch.bitwise_not(torch.unsqueeze(mask, 1))
    embed = self.embed
    _0 = torch.add(torch.matmul(xs, CONSTANTS.c0), CONSTANTS.c1)
                   ~~~~~~~~~~~~ <--- HERE
    input = torch.layer_norm(_0, [1024], CONSTANTS.c2, CONSTANTS.c3)
    pos_enc = embed.pos_enc

Traceback of TorchScript, original code (most recent call last):
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`

  0%|                                                                                            | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\HO\miniconda3\envs\cosyvoice\lib\site-packages\gradio\queueing.py", line 521, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\HO\miniconda3\envs\cosyvoice\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\HO\miniconda3\envs\cosyvoice\lib\site-packages\gradio\blocks.py", line 1945, in process_api
    result = await self.call_function(
  File "C:\Users\HO\miniconda3\envs\cosyvoice\lib\site-packages\gradio\blocks.py", line 1525, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\HO\miniconda3\envs\cosyvoice\lib\site-packages\gradio\utils.py", line 655, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\HO\miniconda3\envs\cosyvoice\lib\site-packages\gradio\utils.py", line 648, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\HO\miniconda3\envs\cosyvoice\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\HO\miniconda3\envs\cosyvoice\lib\site-packages\anyio\_backends\_asyncio.py", line 2364, in run_sync_in_worker_thread
    return await future
  File "C:\Users\HO\miniconda3\envs\cosyvoice\lib\site-packages\anyio\_backends\_asyncio.py", line 864, in run
    result = context.run(func, *args)
  File "C:\Users\HO\miniconda3\envs\cosyvoice\lib\site-packages\gradio\utils.py", line 631, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\HO\miniconda3\envs\cosyvoice\lib\site-packages\gradio\utils.py", line 814, in gen_wrapper
    response = next(iterator)
  File "webui.py", line 120, in generate_audio
    for i in cosyvoice.inference_zero_shot(tts_text, prompt_text, prompt_speech_16k, stream=stream, speed=speed):
  File "E:\AI\CosyVoice\cosyvoice\cli\cosyvoice.py", line 80, in inference_zero_shot
    for model_output in self.model.tts(**model_input, stream=stream, speed=speed):
  File "E:\AI\CosyVoice\cosyvoice\cli\model.py", line 191, in tts
    this_tts_speech = self.token2wav(token=this_tts_speech_token,
  File "E:\AI\CosyVoice\cosyvoice\cli\model.py", line 104, in token2wav
    tts_mel, flow_cache = self.flow.inference(token=token.to(self.device),
  File "C:\Users\HO\miniconda3\envs\cosyvoice\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\AI\CosyVoice\cosyvoice\flow\flow.py", line 116, in inference
    embedding = F.normalize(embedding, dim=1)
  File "C:\Users\HO\miniconda3\envs\cosyvoice\lib\site-packages\torch\nn\functional.py", line 4660, in normalize
    denom = input.norm(p, dim, keepdim=True).clamp_min(eps).expand_as(input)
  File "C:\Users\HO\miniconda3\envs\cosyvoice\lib\site-packages\torch\_tensor.py", line 647, in norm
    return torch.norm(self, p, dim, keepdim, dtype=dtype)
  File "C:\Users\HO\miniconda3\envs\cosyvoice\lib\site-packages\torch\functional.py", line 1517, in norm
    return torch.linalg.vector_norm(input, _p, _dim, keepdim, dtype=dtype)
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
跑不起来，16G显存

**Comment by iloveuaa** [comment]
bug 错误太多了，启动了，但是一大堆报错
