### ISSUE TITLE
ImportError: cannot import name 'Annotated' from 'pydantic.typing'

### ISSUE THREAD

**Issue by neuxys** [FunAudioLLM/CosyVoice#7]
example.py is copied from official example. 

2024-07-05 16:29:50,876 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2024-07-05 16:29:50,876 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-07-05 16:29:52,012 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 51af4c199ce0493bf05f6e6a4c460b07 and a total number of 980 components indexed
transformer is not installed, please install it if you want to use related modules
Traceback (most recent call last):
  File "example.py", line 1, in <module>
    from cosyvoice.cli.cosyvoice import CosyVoice
  File "/mnt/bigclass/project/cosyvoice/CosyVoice/cosyvoice/cli/cosyvoice.py", line 18, in <module>
    from cosyvoice.cli.frontend import CosyVoiceFrontEnd
  File "/mnt/bigclass/project/cosyvoice/CosyVoice/cosyvoice/cli/frontend.py", line 23, in <module>
    import inflect
  File "/mnt/bigclass/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/inflect/__init__.py", line 77, in <module>
    from pydantic.typing import Annotated
ImportError: cannot import name 'Annotated' from 'pydantic.typing' (/mnt/bigclass/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/pydantic/typing.py)

I update pydantic.typing from 2.7.0 to 2.8.3, still ...
Need I add transformers to requirements.txt?

**Comment by DarkLand-Chen** [comment]
File "/mnt/bigclass/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/inflect/init.py", line 77  修改  from pydantic.typing import Annotated  改成 from typing_extensions import Annotated

**Comment by neuxys** [comment]
> File "/mnt/bigclass/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/inflect/init.py", line 77 修改 from pydantic.typing import Annotated 改成 from typing_extensions import Annotated

You are my idol, problem solved.
