### ISSUE TITLE
更新了之后运行示例代码报错 KeyError: 'additional_special_tokens'

### ISSUE THREAD

**Issue by laishujie** [FunAudioLLM/CosyVoice#724]
更新了之后运行示例代码报错
``` python
    cosyvoice = CosyVoice('pretrained_models/CosyVoice-300M-SFT', load_jit=True, load_onnx=False, fp16=True)
    # sft usage
    print(cosyvoice.list_avaliable_spks())
    # change stream=True for chunk stream inference
    for i, j in enumerate(
            cosyvoice.inference_sft('你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？', '中文女', stream=False)):
        torchaudio.save('sft_{}.wav'.format(i), j['tts_speech'], cosyvoice.sample_rate)     
```

```python



failed to import ttsfrd, use WeTextProcessing instead
/home/laisj/anaconda3/envs/cosyvoice_310/lib/python3.10/site-packages/diffusers/models/lora.py:393: FutureWarning: `LoRACompatibleLinear` is deprecated and will be removed in version 1.0.0. Use of `LoRACompatibleLinear` is deprecated. Please switch to PEFT backend by installing PEFT: `pip install peft`.
  deprecate("LoRACompatibleLinear", "1.0.0", deprecation_message)
2024-12-16 14:21:15,695 INFO input frame rate=50
/home/laisj/anaconda3/envs/cosyvoice_310/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
/home/laisj/PycharmProjects/CosyVoice/cosyvoice/dataset/processor.py:24: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend('soundfile')
/home/laisj/anaconda3/envs/cosyvoice_310/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:115: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(
2024-12-16 14:21:16,511 WETEXT INFO found existing fst: /home/laisj/anaconda3/envs/cosyvoice_310/lib/python3.10/site-packages/tn/zh_tn_tagger.fst
2024-12-16 14:21:16,511 INFO found existing fst: /home/laisj/anaconda3/envs/cosyvoice_310/lib/python3.10/site-packages/tn/zh_tn_tagger.fst
2024-12-16 14:21:16,511 WETEXT INFO                     /home/laisj/anaconda3/envs/cosyvoice_310/lib/python3.10/site-packages/tn/zh_tn_verbalizer.fst
2024-12-16 14:21:16,511 INFO                     /home/laisj/anaconda3/envs/cosyvoice_310/lib/python3.10/site-packages/tn/zh_tn_verbalizer.fst
2024-12-16 14:21:16,511 WETEXT INFO skip building fst for zh_normalizer ...
2024-12-16 14:21:16,511 INFO skip building fst for zh_normalizer ...
2024-12-16 14:21:16,658 WETEXT INFO found existing fst: /home/laisj/anaconda3/envs/cosyvoice_310/lib/python3.10/site-packages/tn/en_tn_tagger.fst
2024-12-16 14:21:16,658 INFO found existing fst: /home/laisj/anaconda3/envs/cosyvoice_310/lib/python3.10/site-packages/tn/en_tn_tagger.fst
2024-12-16 14:21:16,658 WETEXT INFO                     /home/laisj/anaconda3/envs/cosyvoice_310/lib/python3.10/site-packages/tn/en_tn_verbalizer.fst
2024-12-16 14:21:16,658 INFO                     /home/laisj/anaconda3/envs/cosyvoice_310/lib/python3.10/site-packages/tn/en_tn_verbalizer.fst
2024-12-16 14:21:16,658 WETEXT INFO skip building fst for en_normalizer ...
2024-12-16 14:21:16,658 INFO skip building fst for en_normalizer ...
Traceback (most recent call last):
  File "/home/laisj/PycharmProjects/CosyVoice/test.py", line 11, in <module>
    for i, j in enumerate(
  File "/home/laisj/PycharmProjects/CosyVoice/cosyvoice/cli/cosyvoice.py", line 63, in inference_sft
    for i in tqdm(self.frontend.text_normalize(tts_text, split=True)):
  File "/home/laisj/PycharmProjects/CosyVoice/cosyvoice/cli/frontend.py", line 113, in text_normalize
    for token in self.tokenizer.special_tokens['additional_special_tokens']:
KeyError: 'additional_special_tokens'
```

**Comment by gongchenghhu** [comment]
Yes, I also found this problem.

**Comment by licycle** [comment]
same question

**Comment by luffy-git** [comment]
me too

**Comment by vjeson** [comment]
me too

**Comment by lang-CN** [comment]
cosyvoice = CosyVoice('pretrained_models/CosyVoice-300M-SFT', load_jit=True, load_onnx=False, fp16=True)
change 
cosyvoice = CosyVoice2('pretrained_models/CosyVoice2-0.5B', load_jit=False, load_onnx=False, load_trt=False)

if you update the code ,you master used CosyVoice2-0.5B model.

webui used CosyVoice2-0.5B can run.
python3 webui.py --port 50000 --model_dir pretrained_models/CosyVoice2-0.5B

After the update, the code can not run the original model. Hope to update earlier

**Comment by lang-CN** [comment]
It is currently possible to generate speech using code execution

cosyvoice = CosyVoice2('pretrained_models/CosyVoice2-0.5B', load_jit=False, load_onnx=False, load_trt=False)




If you want to experience mode2 and used the webUI,this is the error resolution.



















在 2024-12-17 08:48:37，"luffy" ***@***.***> 写道：

used CosyVoice2-0.5B。
image.png (view on web)

**Comment by NBtree** [comment]
> used CosyVoice2-0.5B。 ![image](https://private-user-images.githubusercontent.com/27559016/396320722-e7415700-cf8e-44e6-bfe2-c3e3bd0769be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDY1NTksIm5iZiI6MTczNDQwNjI1OSwicGF0aCI6Ii8yNzU1OTAxNi8zOTYzMjA3MjItZTc0MTU3MDAtY2Y4ZS00NGU2LWJmZTItYzNlM2JkMDc2OWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzMzA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhOGViNmYzMDAwNWFmY2QxNTU0Y2Q0NzEyZjE0ZTJkZDk0NWUxOTQwY2RhMWRlZTQ3MTRkZjZlYTRiMTM2ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GmRbT_Pfl_WK2D2QZwhEKchELz85JZEkMVOV4Q_gN94)

same question.

**Comment by lang-CN** [comment]
Add the picture in the reply
If you want to experience mode2 and used the webUI,this is the error resolution.
@luffy-git 
![image](https://github.com/user-attachments/assets/287a4a91-b9c1-4dfc-88a9-fdd70eca7537)

**Comment by luffy-git** [comment]
> Add the picture in the reply
> If you want to experience mode2 and used the webUI,this is the error resolution.

Okay, I will try. tks

**Comment by MrSupW** [comment]
更新代码后加载cosyvoice1.0就会遇到这个问题。2.0没有问题。感觉是frontend没有适配好不同版本的cosyvoice

**Comment by aiwantaozi** [comment]
Any updates?
