### ISSUE TITLE
使用gitee上的操作运行, 已经启动了, 但是推理的时候还是报错

### ISSUE THREAD

**Issue by 13576245149** [FunAudioLLM/CosyVoice#732]
(cosyvoice) kanjian@CHINAMI-8DD0U1T:/mnt/e/project/CosyVoice$ python test.py
2024-12-16 19:11:22,087 - modelscope - INFO - PyTorch version 2.3.1+cu121 Found.
2024-12-16 19:11:22,089 - modelscope - INFO - Loading ast index from /home/kanjian/.cache/modelscope/ast_indexer
2024-12-16 19:11:22,103 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 4ae05c647592e26410041c8cc03dcd48 and a total number of 980 components indexed
failed to import ttsfrd, use WeTextProcessing instead
/home/kanjian/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/diffusers/models/lora.py:393: FutureWarning: `LoRACompatibleLinear` is deprecated and will be removed in version 1.0.0. Use of `LoRACompatibleLinear` is deprecated. Please switch to PEFT backend by installing PEFT: `pip install peft`.
  deprecate("LoRACompatibleLinear", "1.0.0", deprecation_message)
2024-12-16 19:11:26,793 INFO input frame rate=50
/home/kanjian/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
/mnt/e/project/CosyVoice/cosyvoice/dataset/processor.py:24: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend('soundfile')
2024-12-16 19:11:30.217968167 [W:onnxruntime:, transformer_memcpy.cc:74 ApplyImpl] 12 Memcpy nodes are added to the graph main_graph for CUDAExecutionProvider. It might have negative impact on performance (including unable to run CUDA graph). Set session_options.log_severity_level=1 to see the detail logs before this message.
2024-12-16 19:11:30.218743010 [W:onnxruntime:, session_state.cc:1166 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-12-16 19:11:30.218764126 [W:onnxruntime:, session_state.cc:1168 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
2024-12-16 19:11:30,357 WETEXT INFO found existing fst: /home/kanjian/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/tn/zh_tn_tagger.fst
2024-12-16 19:11:30,357 INFO found existing fst: /home/kanjian/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/tn/zh_tn_tagger.fst
2024-12-16 19:11:30,357 WETEXT INFO                     /home/kanjian/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/tn/zh_tn_verbalizer.fst
2024-12-16 19:11:30,357 INFO                     /home/kanjian/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/tn/zh_tn_verbalizer.fst
2024-12-16 19:11:30,357 WETEXT INFO skip building fst for zh_normalizer ...
2024-12-16 19:11:30,357 INFO skip building fst for zh_normalizer ...
2024-12-16 19:11:30,517 WETEXT INFO found existing fst: /home/kanjian/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/tn/en_tn_tagger.fst
2024-12-16 19:11:30,517 INFO found existing fst: /home/kanjian/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/tn/en_tn_tagger.fst
2024-12-16 19:11:30,517 WETEXT INFO                     /home/kanjian/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/tn/en_tn_verbalizer.fst
2024-12-16 19:11:30,517 INFO                     /home/kanjian/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/tn/en_tn_verbalizer.fst
2024-12-16 19:11:30,517 WETEXT INFO skip building fst for en_normalizer ...
2024-12-16 19:11:30,517 INFO skip building fst for en_normalizer ...
  0%|                                                                                             | 0/1 [00:00<?, ?it/s]2024-12-16 19:11:35,919 INFO synthesis text 收到好友从远方寄来的生日礼物,那份意外的惊喜与深深的祝福让我心中充满了甜蜜的 快乐,笑容如花般绽放。
  0%|                                                                                             | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/e/project/CosyVoice/test.py", line 9, in <module>
    for i, j in enumerate(cosyvoice2.inference_zero_shot('收到好友从远方寄来的生日礼物，那份意外的惊喜与深深的祝福让我心中充满了甜蜜的快乐，笑容如花儿般绽放。', '希望你以后能够做的比我还好呦。', prompt_speech_16k, stream=True)):
  File "/mnt/e/project/CosyVoice/cosyvoice/cli/cosyvoice.py", line 81, in inference_zero_shot
    for model_output in self.model.tts(**model_input, stream=stream, speed=speed):
  File "/mnt/e/project/CosyVoice/cosyvoice/cli/model.py", line 164, in tts
    this_tts_speech = self.token2wav(token=this_tts_speech_token,
  File "/mnt/e/project/CosyVoice/cosyvoice/cli/model.py", line 104, in token2wav
    tts_mel, flow_cache = self.flow.inference(token=token.to(self.device),
  File "/home/kanjian/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/e/project/CosyVoice/cosyvoice/flow/flow.py", line 137, in inference
    feat, flow_cache = self.decoder(
  File "/home/kanjian/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kanjian/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kanjian/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/e/project/CosyVoice/cosyvoice/flow/flow_matching.py", line 68, in forward
    return self.solve_euler(z, t_span=t_span, mu=mu, mask=mask, spks=spks, cond=cond), flow_cache
  File "/mnt/e/project/CosyVoice/cosyvoice/flow/flow_matching.py", line 113, in solve_euler
    dphi_dt = self.forward_estimator(
  File "/mnt/e/project/CosyVoice/cosyvoice/flow/flow_matching.py", line 132, in forward_estimator
    return self.estimator.forward(x, mask, mu, t, spks, cond)
  File "/mnt/e/project/CosyVoice/cosyvoice/flow/decoder.py", line 253, in forward
    attn_mask = add_optional_chunk_mask(x, mask_down.bool(), False, False, 0, self.static_chunk_size, -1)
  File "/home/kanjian/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'ConditionalDecoder' object has no attribute 'static_chunk_size'

**Comment by gongchenghhu** [comment]
+1

**Comment by MrSupW** [comment]
+1 还是不同版本的适配问题，cosyvoice2没有问题，但是cosyvoice会有这个问题

**Comment by 13576245149** [comment]
我运行的就是cosyvoice2, 一直报这个错误, 模型地址:CosyVohttps://www.modelscope.cn/models/iic/CosyVoice2-0.5B/summaryice语音生成大模型2.0-0.5B · 模型库&nbsp;


枫秋落叶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "He ***@***.***&gt;; 
发送时间: 2024年12月17日(星期二) 下午3:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FunAudioLLM/CosyVoice] 使用gitee上的操作运行, 已经启动了, 但是推理的时候还是报错AttributeError: &#39;ConditionalDecoder&#39; object has no attribute &#39;static_chunk_size&#39; (Issue #732)














 
+1 还是不同版本的适配问题，cosyvoice2没有问题，但是cosyvoice会有这个问题

**Comment by housebaby** [comment]
Traceback (most recent call last):
  File "/data/private/workspace/CosyVoice/test.py", line 31, in <module>
    for i, j in enumerate(cosyvoice.inference_sft('你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？', '中文女', stream=False)):
  File "/data/private/workspace/CosyVoice/cosyvoice/cli/cosyvoice.py", line 67, in inference_sft
    for model_output in self.model.tts(**model_input, stream=stream, speed=speed):
  File "/data/private/workspace/CosyVoice/cosyvoice/cli/model.py", line 191, in tts
    this_tts_speech = self.token2wav(token=this_tts_speech_token,
  File "/data/private/workspace/CosyVoice/cosyvoice/cli/model.py", line 104, in token2wav
    tts_mel, flow_cache = self.flow.inference(token=token.to(self.device),
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data/private/workspace/CosyVoice/cosyvoice/flow/flow.py", line 137, in inference
    feat, flow_cache = self.decoder(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data/private/workspace/CosyVoice/cosyvoice/flow/flow_matching.py", line 68, in forward
    return self.solve_euler(z, t_span=t_span, mu=mu, mask=mask, spks=spks, cond=cond), flow_cache
  File "/data/private/workspace/CosyVoice/cosyvoice/flow/flow_matching.py", line 113, in solve_euler
    dphi_dt = self.forward_estimator(
  File "/data/private/workspace/CosyVoice/cosyvoice/flow/flow_matching.py", line 132, in forward_estimator
    return self.estimator.forward(x, mask, mu, t, spks, cond)
  File "/data/private/workspace/CosyVoice/cosyvoice/flow/decoder.py", line 253, in forward
    attn_mask = add_optional_chunk_mask(x, mask_down.bool(), False, False, 0, self.static_chunk_size, -1)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'ConditionalDecoder' object has no attribute 'static_chunk_size

**Comment by Jandown** [comment]
clone最新的就好了，1个小时前作者更新了

**Comment by 13576245149** [comment]
好的，这就试一下








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年12月17日(周二) 下午5:22写道:

  

 
clone最新的就好了，1个小时前作者更新了

**Comment by HaiFengZeng** [comment]
self.static_chunk_size=100吧，这个是默认设置的，测试下25也可以
