### ISSUE TITLE
pip install -r requirements.txt failed on MacOS for CosyVoice 2.0

### ISSUE THREAD

**Issue by tonyjohnvan** [FunAudioLLM/CosyVoice#734]
**Describe the bug**

`pip install -r requirements.txt` error with cosy voice 2 on Mac M series chip

**To Reproduce**
1. `pip install -r requirements.txt` on conda env with python3.10 and 
2. See error
```
//..... omit working ones
Collecting tensorrt-cu12==10.0.1 (from -r requirements.txt (line 29))
  Downloading tensorrt-cu12-10.0.1.tar.gz (18 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/7n/4lmz95mj5f7f5x72cjnzhgjc0000gn/T/pip-install-zar0x9ap/tensorrt-cu12_00b1596c6376441eacc9ab3a630be378/setup.py", line 63, in <module>
          raise RuntimeError("TensorRT currently only builds wheels for Linux and Windows")
      RuntimeError: TensorRT currently only builds wheels for Linux and Windows
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Expected behavior**
`pip install -r requirements.txt` should working

**Screenshots**
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/a76df647-cdff-47d2-8e82-6ef21cb0f42b" />

**Desktop (please complete the following information):**
 - OS: macOS Sequoia
 - Version: Version 15.1.1

**Additional context**
N/a

**Comment by tonyjohnvan** [comment]
yes understood, I bypass it and can still use the CosyVoice2, it's really awesome in every way! Great job done! really appreciated! 
However, I found there is only one model available for the V2, and I'm most interested in the SFT model, any plan for releasing one soon or any tutorial of how to train one myself? thanks very much in advance!

**Comment by lonelygo** [comment]
我fork 的版本提供了 macOS 下的支持，你可以试试看：https://github.com/lonelygo/CosyVoice
