### ISSUE TITLE
ttsfrd-0.4.2-cp310-cp310-linux_x86_64.whl 这个对应的 windows11下的文件是那个 是否可以给个下载地址

### ISSUE THREAD

**Issue by anstonjie** [FunAudioLLM/CosyVoice#737]
ttsfrd-0.4.2-cp310-cp310-linux_x86_64.whl 这个对应的 windows11下的文件是那个 是否可以给个下载地址

**Comment by Jandown** [comment]
ttsfrd不支持win，win不用管，会自动跳过使用WeTextProcessing替代，不影响使用

**Comment by zhlgx** [comment]
我的这个是什么问题？


M:\AIII\CosyVoice\zhlgx\lib\site-packages\diffusers\models\lora.py:393: FutureWarning: `LoRACompatibleLinear` is deprecated and will be removed in version 1.0.0. Use of `LoRACompatibleLinear` is deprecated. Please switch to PEFT backend by installing PEFT: `pip install peft`.
  deprecate("LoRACompatibleLinear", "1.0.0", deprecation_message)
2025-01-03 23:50:20,338 INFO input frame rate=50
M:\AIII\CosyVoice\zhlgx\lib\site-packages\torch\nn\utils\weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
M:\AIII\CosyVoice\cosyvoice\dataset\processor.py:24: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend('soundfile')
M:\AIII\CosyVoice\cosyvoice\cli\frontend.py:57: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.spk2info = torch.load(spk2info, map_location=self.device)
Traceback (most recent call last):
  File "M:\AIII\CosyVoice\webui.py", line 187, in <module>
    cosyvoice = CosyVoice2(args.model_dir) if 'CosyVoice2' in args.model_dir else CosyVoice(args.model_dir)
  File "M:\AIII\CosyVoice\cosyvoice\cli\cosyvoice.py", line 36, in __init__
    self.frontend = CosyVoiceFrontEnd(configs['get_tokenizer'],
  File "M:\AIII\CosyVoice\cosyvoice\cli\frontend.py", line 63, in __init__
    self.frd = ttsfrd.TtsFrontendEngine()
AttributeError: module 'ttsfrd' has no attribute 'TtsFrontendEngine'
