### ISSUE TITLE
"no such entity as torchaudio.functional.compute_kaldi_pitch" in cosyvoice2 with python 3.10

### ISSUE THREAD

**Issue by GrahamHuang3** [FunAudioLLM/CosyVoice#758]
Traceback (most recent call last):
  File "/mnt/d/work/CosyVoice2/examples/libritts/cosyvoice/../../../cosyvoice/bin/train.py", line 170, in <module>
    main()
  File "/home/huangxu/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/mnt/d/work/CosyVoice2/examples/libritts/cosyvoice/../../../cosyvoice/bin/train.py", line 101, in main
    configs = load_hyperpyyaml(f, overrides=override_dict)
  File "/home/huangxu/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/hyperpyyaml/core.py", line 188, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=loader)
  File "/home/huangxu/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/huangxu/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 116, in get_single_data
    return self.construct_document(node)
  File "/home/huangxu/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 120, in construct_document
    data = self.construct_object(node)
  File "/home/huangxu/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/home/huangxu/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "/home/huangxu/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 633, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/huangxu/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/home/huangxu/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/huangxu/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/home/huangxu/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "/home/huangxu/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/hyperpyyaml/core.py", line 491, in _construct_name
    raise ImportError("There is no such entity as %s" % callable_string)
ImportError: There is no such entity as torchaudio.functional.compute_kaldi_pitch

Anyone meeting the same problem? How to solve it?

**Comment by aluminumbox** [comment]
后面会找一个替代torchaudio计算pitch的，急着用的话可以用torchaudio2.0.2训练，然后用高版本torch部署

**Comment by libo5410391** [comment]
换成torchaudio2.0.2后，torch也会自动降版本，然后就会出现新的错误：TypeError: CosyVoiceModel.__init__() missing 1 required positional argument: 'fp16'

**Comment by LiuMingYy** [comment]
> 换成torchaudio2.0.2后，torch也会自动降版本，然后就会出现新的错误：TypeError: CosyVoiceModel.**init**() missing 1 required positional argument: 'fp16'

大佬，请问最终如何解决的呢
