### ISSUE TITLE
Ubuntu：22.04 64位、Cuda版本：12.4.1、Python：3.10，部署Web启动报错

### ISSUE THREAD

**Issue by liujunyang0919** [FunAudioLLM/CosyVoice#781]
Traceback (most recent call last):
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/pydoc.py", line 439, in safeimport
    module = __import__(path)
  File "/root/CosyVoice/cosyvoice/flow/flow_matching.py", line 17, in <module>
    from matcha.models.components.flow_matching import BASECFM
  File "/root/CosyVoice/third_party/Matcha-TTS/matcha/models/components/flow_matching.py", line 6, in <module>
    from matcha.models.components.decoder import Decoder
  File "/root/CosyVoice/third_party/Matcha-TTS/matcha/models/components/decoder.py", line 8, in <module>
    from diffusers.models.activations import get_activation
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/diffusers/utils/__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/huggingface_hub/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/CosyVoice/webui.py", line 184, in <module>
    cosyvoice = CosyVoice2(args.model_dir) if 'CosyVoice2' in args.model_dir else CosyVoice(args.model_dir)
  File "/root/CosyVoice/cosyvoice/cli/cosyvoice.py", line 33, in __init__
    configs = load_hyperpyyaml(f)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/hyperpyyaml/core.py", line 188, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=loader)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 116, in get_single_data
    return self.construct_document(node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 120, in construct_document
    data = self.construct_object(node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 633, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/hyperpyyaml/core.py", line 480, in _construct_object
    args, kwargs = _load_node(loader, node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/hyperpyyaml/core.py", line 434, in _load_node
    kwargs = loader.construct_mapping(node, deep=True)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/hyperpyyaml/core.py", line 470, in _construct_object
    callable_ = pydoc.locate(callable_string)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/pydoc.py", line 1719, in locate
    nextmodule = safeimport('.'.join(parts[:n+1]), forceload)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/pydoc.py", line 454, in safeimport
    raise ErrorDuringImport(path, sys.exc_info())
pydoc.ErrorDuringImport: problem in cosyvoice.flow.flow_matching - ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/huggingface_hub/__init__.py)
(cosyvoice) root@iZbp188pe16rhhu1bsrpqoZ:~/CosyVoice# ^C
(cosyvoice) root@iZbp188pe16rhhu1bsrpqoZ:~/CosyVoice# export PYTHONPATH=third_party/Matcha-TTS
(cosyvoice) root@iZbp188pe16rhhu1bsrpqoZ:~/CosyVoice# python3 webui.py --port 50000 --model_dir pretrained_models/CosyVoice-300M
2024-12-24 16:21:49,538 - modelscope - INFO - PyTorch version 2.3.1+cu121 Found.
2024-12-24 16:21:49,539 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-12-24 16:21:49,565 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 3ce5ade1142f68ac3b09c2102132cae5 and a total number of 980 components indexed
Traceback (most recent call last):
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/pydoc.py", line 439, in safeimport
    module = __import__(path)
  File "/root/CosyVoice/cosyvoice/flow/flow_matching.py", line 17, in <module>
    from matcha.models.components.flow_matching import BASECFM
  File "/root/CosyVoice/third_party/Matcha-TTS/matcha/models/components/flow_matching.py", line 6, in <module>
    from matcha.models.components.decoder import Decoder
  File "/root/CosyVoice/third_party/Matcha-TTS/matcha/models/components/decoder.py", line 8, in <module>
    from diffusers.models.activations import get_activation
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/diffusers/utils/__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/huggingface_hub/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/CosyVoice/webui.py", line 184, in <module>
    cosyvoice = CosyVoice2(args.model_dir) if 'CosyVoice2' in args.model_dir else CosyVoice(args.model_dir)
  File "/root/CosyVoice/cosyvoice/cli/cosyvoice.py", line 33, in __init__
    configs = load_hyperpyyaml(f)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/hyperpyyaml/core.py", line 188, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=loader)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 116, in get_single_data
    return self.construct_document(node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 120, in construct_document
    data = self.construct_object(node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 633, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/hyperpyyaml/core.py", line 480, in _construct_object
    args, kwargs = _load_node(loader, node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/hyperpyyaml/core.py", line 434, in _load_node
    kwargs = loader.construct_mapping(node, deep=True)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/hyperpyyaml/core.py", line 470, in _construct_object
    callable_ = pydoc.locate(callable_string)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/pydoc.py", line 1719, in locate
    nextmodule = safeimport('.'.join(parts[:n+1]), forceload)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/pydoc.py", line 454, in safeimport
    raise ErrorDuringImport(path, sys.exc_info())
pydoc.ErrorDuringImport: problem in cosyvoice.flow.flow_matching - ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/huggingface_hub/__init__.py)

**Comment by shirubei** [comment]
从 ImportError: cannot import name 'cached_download' from 'huggingface_hub' 看估计是包的版本不匹配吧

**Comment by aluminumbox** [comment]
可以先git clone下载一下，后面会修复一下版本

**Comment by wangckyo** [comment]
降级后报错消失了，pip install huggingface_hub==0.24.7

**Comment by xulu666666** [comment]
请问安装下边的依赖了吗？🤔️，安装不了呢，谢谢
tensorrt-cu12==10.0.1; sys_platform == 'linux'
tensorrt-cu12-bindings==10.0.1; sys_platform == 'linux'
tensorrt-cu12-libs==10.0.1; sys_platform == 'linux'

**Comment by UniDel7a** [comment]
> 请问安装下边的依赖了吗？🤔️，安装不了呢，谢谢 tensorrt-cu12==10.0.1; sys_platform == 'linux' tensorrt-cu12-bindings==10.0.1; sys_platform == 'linux' tensorrt-cu12-libs==10.0.1; sys_platform == 'linux'

刚刚几乎遇到了同样的问题，不过解决了，请问“安装不了“的具体情况是什么呢？如果是指长时间没有响应的话，那么这个属于正常现象，因为单单tensorrt-cu12-libs的.whl文件就有1G多大小。如果不是的话，也请将控制台返回信息透露一下。
