### ISSUE TITLE
使用grpc方式启动CosyVoice2报错

### ISSUE THREAD

**Issue by guo-hai** [FunAudioLLM/CosyVoice#791]
如下图片所示，使用grpc的方式启动CosyVoice服务，使用的最新2的模型数据，报如下错：

```
(cosyvoice) root@yang:~/CosyVoice/runtime/python/grpc# python server.py --port 50000 --model_dir /root/CosyVoice/pretrained_models/CosyVoice2-0.5B
2024-12-26 09:18:13,110 - modelscope - INFO - PyTorch version 2.3.1+cu121 Found.
2024-12-26 09:18:13,110 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-12-26 09:18:13,139 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 521576be7bc5622e25541760ef2c2619 and a total number of 980 components indexed
failed to import ttsfrd, use WeTextProcessing instead
-------------
Traceback (most recent call last):
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/transformers/utils/hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: ''.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/CosyVoice/runtime/python/grpc/server.py", line 91, in <module>
    main()
  File "/root/CosyVoice/runtime/python/grpc/server.py", line 70, in main
    cosyvoice_pb2_grpc.add_CosyVoiceServicer_to_server(CosyVoiceServiceImpl(args), grpcServer)
  File "/root/CosyVoice/runtime/python/grpc/server.py", line 36, in __init__
    self.cosyvoice = CosyVoice(args.model_dir)
  File "/root/CosyVoice/runtime/python/grpc/../../../cosyvoice/cli/cosyvoice.py", line 33, in __init__
    configs = load_hyperpyyaml(f)
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/hyperpyyaml/core.py", line 188, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=loader)
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 116, in get_single_data
    return self.construct_document(node)
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 120, in construct_document
    data = self.construct_object(node)
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 633, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/hyperpyyaml/core.py", line 480, in _construct_object
    args, kwargs = _load_node(loader, node)
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/hyperpyyaml/core.py", line 434, in _load_node
    kwargs = loader.construct_mapping(node, deep=True)
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/hyperpyyaml/core.py", line 481, in _construct_object
    return callable_(*args, **kwargs)
  File "/root/CosyVoice/runtime/python/grpc/../../../cosyvoice/llm/llm.py", line 223, in __init__
    self.model = Qwen2ForCausalLM.from_pretrained(pretrain_path)
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3015, in from_pretrained
    resolved_config_file = cached_file(
  File "/root/anaconda3/envs/cosyvoice/lib/python3.10/site-packages/transformers/utils/hub.py", line 462, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: ''. Please provide either the path to a local folder or the repo_id of a model on the Hub.
```
从日志来看，是什么东西为空了。使用源码debug，最后发现grpc方式会加载模型中的cosyvoice.yaml文件，并且获取里面的配置信息，打开该文件：
```
# set random seed, so that you may reproduce your result.
__set_seed1: !apply:random.seed [1986]
__set_seed2: !apply:numpy.random.seed [1986]
__set_seed3: !apply:torch.manual_seed [1986]
__set_seed4: !apply:torch.cuda.manual_seed_all [1986]

# fixed params
sample_rate: 24000
llm_input_size: 896
llm_output_size: 896
spk_embed_dim: 192
qwen_pretrain_path: ''

# model params
# for all class/function included in this repo, we use !<name> or !<new> for intialization, so that user may find all corresponding class/function according to one single yaml.
# for system/third_party class/function, we do not require this.
llm: !new:cosyvoice.llm.llm.Qwen2LM
    llm_input_size: !ref <llm_input_size>
    llm_output_size: !ref <llm_output_size>
    speech_token_size: 6561
    length_normalized_loss: True
    lsm_weight: 0
    llm: !new:cosyvoice.llm.llm.Qwen2Encoder
        pretrain_path: !ref <qwen_pretrain_path>
    sampling: !name:cosyvoice.utils.common.ras_sampling
        top_p: 0.8
        top_k: 25
        win_size: 10
        tau_r: 0.1

flow: !new:cosyvoice.flow.flow.CausalMaskedDiffWithXvec
    input_size: 512
    output_size: 80
    spk_embed_dim: !ref <spk_embed_dim>
    output_type: 'mel'
    vocab_size: 6561
    input_frame_rate: 25
    only_mask_loss: True
    token_mel_ratio: 2
    pre_lookahead_len: 3
```
里面的qwen_pretrain_path: '' 果然是空，导致上面启动报错，请问这个配置是干嘛的？ 如何解决上述启动报错问题？

**Comment by WendongGan** [comment]
同关注这个问题，假如cosyvoice2要部署grpc服务的话，怎么操作呢？

**Comment by sunbeibei-hub** [comment]
同问

**Comment by sunbeibei-hub** [comment]
![image](https://github.com/user-attachments/assets/713dd7a6-9546-44bb-9a14-436d44c702db)
这里需要指定使用CosyVoice2的模型加载器

**Comment by guo-hai** [comment]
> ![image](https://private-user-images.githubusercontent.com/89978551/398837605-713dd7a6-9546-44bb-9a14-436d44c702db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODQ2MzksIm5iZiI6MTczNTI4NDMzOSwicGF0aCI6Ii84OTk3ODU1MS8zOTg4Mzc2MDUtNzEzZGQ3YTYtOTU0Ni00NGJiLTlhMTQtNDM2ZDQ0YzcwMmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDA3MjUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkN2I4ZWZiNWEzNDNmYjRjNTdmMWEwMjdiNjkxOGFmMDUwYjJlZmUzZDU4YTQ3YmViNjJlNDZkMThlZDM1NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hHiHY-ZfZwliPd3aKTCHAGQPNHXRzWUV1CbQvQyPAak) 这里需要指定使用CosyVoice2的模型加载器

好像确实如此

**Comment by aluminumbox** [comment]
这是因为cosyvoice和cosyvoice2的初始化方式不同，目前需要用户自己修改一下
