### ISSUE TITLE
使用inference_zero_shot 报错

### ISSUE THREAD

**Issue by yingshow** [FunAudioLLM/CosyVoice#803]
Traceback (most recent call last):
  File "/opt/work/test.py", line 15, in <module>
    for i, j in enumerate(cosyvoice.inference_zero_shot(text, prompt_speech_text, prompt_speech_16k, stream=False)):
  File "/opt/work/cosyvoice/cli/cosyvoice.py", line 81, in inference_zero_shot
    for model_output in self.model.tts(**model_input, stream=stream, speed=speed):
  File "/opt/work/cosyvoice/cli/model.py", line 412, in tts
    this_tts_speech = self.token2wav(token=this_tts_speech_token,
  File "/opt/work/cosyvoice/cli/model.py", line 335, in token2wav
    tts_mel, _ = self.flow.inference(token=token.to(self.device),
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/work/cosyvoice/flow/flow.py", line 207, in inference
    token = self.input_embedding(torch.clamp(token, min=0)) * mask
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/sparse.py", line 163, in forward
    return F.embedding(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 2264, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.cuda.FloatTensor instead (while checking arguments for embedding)

使用的句子：图片的精准控制目前已经差不多成熟了，所以接下来大牛们都开始折腾这个视频了。图片对物理世界规律要求是很低的，但视频不一样，每个动起来的东西都要遵守物理世界规律，所以就大体上有两个分支，一个分支就是让大模型充分学习足够多的视频来模拟物理世界里的可能变化（目前是主流，SORA就是这样的）。另一个分支就是如这个Motion类似的进行人为控制行为，通过补帧补绘的方式进来生成。

**Comment by aluminumbox** [comment]
prompt音频以及对应文字也传一下

**Comment by yingshow** [comment]
[语音 241228_183134.zip](https://github.com/user-attachments/files/18269160/241228_183134.zip)
对应的文字：日本汽车制造商本田和日产近日宣布计划联合组建全球第三大汽车制造商。两家公司于12月23号上午签署了一份谅解备忘录。

**Comment by aluminumbox** [comment]
prompt太长了，注意看日志里的warning

**Comment by yingshow** [comment]
> prompt太长了，注意看日志里的warning

之前我也用了一个长prompt但是会自动进行分段处理？那分段的依据是什么？还有长度多少之内？

**Comment by aluminumbox** [comment]
看frontend.py里的代码，前端部分可以自行调整逻辑

**Comment by huskyachao** [comment]
@yingshow 老哥你好，我也遇到了类似的问题，请问你解决了吗？
