### ISSUE TITLE
When I run "python webui_en.py --port 50000 --model_dir pretrained_models/CosyVoice-300M", I got the following error: ImportError: cannot import name 'speed_change' from 'cosyvoice.utils.file_utils'

### ISSUE THREAD

**Issue by Tezozomoctli** [FunAudioLLM/CosyVoice#805]
I have received the following error after setting up the environment, running:

(cosyvoice) C:\Users\Voice AI\CosyVoice\CosyVoice>python webui_en.py --port 50000 --model_dir pretrained_models/CosyVoice2-0.5B
2024-12-29 14:32:43,422 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2024-12-29 14:32:43,422 - modelscope - INFO - Loading ast index from C:\Users\cache\modelscope\ast_indexer
2024-12-29 14:32:43,502 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 e984593bb28b11d497107b234faae6c2 and a total number of 980 components indexed
C:\Users\conda\envs\cosyvoice\lib\site-packages\torchvision\datapoints\__init__.py:12: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)
C:\Users\conda\envs\cosyvoice\lib\site-packages\torchvision\transforms\v2\__init__.py:54: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)
failed to import ttsfrd, use WeTextProcessing instead
Traceback (most recent call last):
  File "C:\Users\Voice AI\CosyVoice\CosyVoice\webui_en.py", line 28, in <module>
    from cosyvoice.utils.file_utils import load_wav, speed_change, logging
ImportError: cannot import name 'speed_change' from 'cosyvoice.utils.file_utils' (C:\Users\Voice AI\CosyVoice\CosyVoice\cosyvoice\utils\file_utils.py)

My error seems very similar to these other ones people have brought up. Mine is slightly different in that it is about cosyvoice.utils.file_utils instead of huggingface :

https://github.com/FunAudioLLM/CosyVoice/issues/123#issue-2406818291
https://github.com/FunAudioLLM/CosyVoice/issues/527#issue-2601293308
https://github.com/FunAudioLLM/CosyVoice/issues/516#issue-2597602383

So I assume I will have to do something similar and revert a version of something to an older one? I just have no idea what to do.

The reason why I have "python webui_en.py" instead of "python3 webui.py" is because this tutorial told me to:
https://www.youtube.com/watch?v=7WblOkOxkXU

Thank you,

**Comment by Tezozomoctli** [comment]
Okay, this time I ran:
python webui.py --port 50000 --model_dir pretrained_models/CosyVoice-300M

I then got the familiar: "ImportError: cannot import name 'cached_download' from 'huggingface_hub' "

So, I did "pip install huggingface_hub==0.24.7", it fixed the issue.

But now I got a new issue:
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained_models/CosyVoice-300M/llm.pt'

**Comment by aluminumbox** [comment]
we dont have webui_en.py in our repo

**Comment by Tezozomoctli** [comment]
> we dont have webui_en.py in our repo

Correct, I did the correct webui.py but I got this new error:

`FileNotFoundError: [Errno 2] No such file or directory: 'pretrained_models/CosyVoice-300M/llm.p`

**Comment by aluminumbox** [comment]
> > we dont have webui_en.py in our repo
> 
> Correct, I changed it to tthe correct one "webui.py" but I got this new error:
> 
> `FileNotFoundError: [Errno 2] No such file or directory: 'pretrained_models/CosyVoice-300M/llm.p`

check readme for usage, follow install instruction

**Comment by zhlgx** [comment]
设置环境哪里不对啊！
运行：python webui.py --port 50000 --model_dir pretrained_models/CosyVoice-300M
错误：
安装成功！
Traceback (most recent call last):
  File "M:\AIII\CosyVoice\webui.py", line 25, in <module>
    from cosyvoice.cli.cosyvoice import CosyVoice, CosyVoice2
  File "M:\AIII\CosyVoice\cosyvoice\cli\cosyvoice.py", line 20, in <module>
    from cosyvoice.cli.frontend import CosyVoiceFrontEnd
  File "M:\AIII\CosyVoice\cosyvoice\cli\frontend.py", line 19, in <module>
    import whisper
  File "M:\AIII\CosyVoice\zhlgx\lib\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
  File "M:\AIII\CosyVoice\zhlgx\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable

说是环境错误！
但是我按照readme来做本地部署的，已经重做了2次，仍然是这个错误！

**Comment by Tezozomoctli** [comment]
@zhlgx 
您是否能够解决 CosyVoice 的 TypeError: argument of type 'NoneType' is not iterable 问题？

**Comment by zhlgx** [comment]
无法解决发自我的手机-------- 原始邮件 --------发件人： Tezozomoctli ***@***.***>日期： 2025年2月16日周日 09:51收件人： FunAudioLLM/CosyVoice ***@***.***>抄送： zhlgx ***@***.***>, Mention ***@***.***>主    题： Re: [FunAudioLLM/CosyVoice] When I run "python webui_en.py --port 50000 --model_dir pretrained_models/CosyVoice-300M", I got the following error: ImportError: cannot import name 'speed_change' from 'cosyvoice.utils.file_utils' (Issue #805)
  @zhlgx
您是否能够解决 CosyVoice 的 TypeError: argument of type 'NoneType' is not iterable 问题？—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>



Tezozomoctli left a comment (FunAudioLLM/CosyVoice#805)
@zhlgx
您是否能够解决 CosyVoice 的 TypeError: argument of type 'NoneType' is not iterable 问题？
