### ISSUE TITLE
官方的 例子中 prompt_speech_16k = load_wav('zero_shot_prompt.wav', 16000) zero_shot_prompt.wav 这个声音文件 为啥换成 七牛云的地址 就报错误？

### ISSUE THREAD

**Issue by anstonjie** [FunAudioLLM/CosyVoice#89]
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ai\CosyVoice_For_Windows\cosyVoice_api.py", line 104, in create_item
    timestampWav = future.result()
                   ^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ai\CosyVoice_For_Windows\cosyVoice_api.py", line 70, in generate_audio
    prompt_speech_16k = load_wav(request.promptAudio, 16000)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ai\CosyVoice_For_Windows\cosyvoice\utils\file_utils.py", line 36, in load_wav
    speech, sample_rate = torchaudio.load(wav)
                          ^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\torchaudio\_backend\utils.py", line 205, in load
    return backend.load(uri, frame_offset, num_frames, normalize, channels_first, format, buffer_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\torchaudio\_backend\soundfile.py", line 27, in load
    return soundfile_backend.load(uri, frame_offset, num_frames, normalize, channels_first, format)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\torchaudio\_backend\soundfile_backend.py", line 221, in load
    with soundfile.SoundFile(filepath, "r") as file_:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\soundfile.py", line 740, in __init__
    self._file = self._open(file, mode_int, closefd)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\soundfile.py", line 1264, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "C:\ProgramData\anaconda3\envs\cosyvoice\Lib\site-packages\soundfile.py", line 1455, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'http://newnvwa2.iteapet.cn/20240710_113507.wav': System error.

**Comment by anstonjie** [comment]
是不是只能用本地的音频文件

**Comment by aluminumbox** [comment]
> 是不是只能用本地的音频文件

yes, we do not support web url
